* notes
transhumanists are regarded as suspicious because they wish to apply the cure

yet transhumanists don't want just to apply the cure to the disabled, they want to apply the cure to everyone

this essay argues that we should regard the able as part of disability studies because interactions between the individual and the environment are always negotiated

accessibility describes the space between an individual and a normative goal. hacking describes the space between an indivudual and a non-normative goal. 


transhumanists and the cure
we are all disabled, all is negotiation
hacking is exclusionary
hacking is inclusionary
we're already hackers, let's act like it
hacking as rhetoric
** The Needs of the Disabled Many

"Isn't it better not to be disabled?" The answer to this question is more complicated than it seems, and theanswer differs based on whether you're talking about 



XXX section on why I give a shit about this XXX

* quotes
** stallman interview
RMS: It means someone who enjoys playful cleverness, especially in programming but other media are also possible. In the 14th century, Guillaume de Machaut wrote a palindromic three-part musical composition. It sounded good, too—I think I played in it once, because I still remember one of the parts. I think that was a good hack. I heard somewhere that J. S. Bach did something similar.
One possible arena for playful cleverness is breaking security. Hackers never had much respect for bureaucratic restrictions. If the computer was sitting idle because the administrators wouldn't let them use it, they would sometimes figure out how to bypass the obstacles and use it anyway. If this required cleverness, it would be fun in itself, as well as making it possible to do other hacking (for instance, useful work) on the computer instead of twiddling one's thumbs. But not all hackers did security breaking. Many never were interested in that. 
[[https://www.gnu.org/philosophy/rms-hack.html][interview with richard stallman]]
** hackers
Peter Samson and his friends had grown up with a specific relationship to the world, wherein things had meaning only if you found out how they worked. And how would you go about that if not by getting your hands on them?

** kurzweil
*** spiritual machines
It is the applications of the technology benefiting disabled people that have brought me the greatest gratification. There is a fortuitous match between the capabilities of contemporary computers and the needs of a disabled person. We're not creating cybernetic geniuses today—not yet. The intelligence of our present-day intelligent computers is narrow, which can provide effective solutions for the narrow deficits of most disabled persons. The restricted intelligence of the machine works effectively with the broad and flexible intelligence of the disabled person. Overcoming the handicaps associated with disabilities using AI technologies has long been a personal goal of mine. With regard to the major physical and sensory disabilities, I believe that in a couple of decades we will come to herald the effective end of handicaps. As amplifiers of human thought, computers have great potential to assist human expression and to expand creativity for all of us. I hope to continue playing a role in harnessing this potential. (Kurzweil 128)

Deaf persons—or anyone with a hearing impairment—commonly use portable speech-to-text listening machines, which display a real-time transcription of what people are saying. The deaf user has the choice of either reading the transcribed speech as displayed text, or watching an animated person gesturing in sign language. These have eliminated the primary communication handicap associated with deafness. Listening machines can also translate what is being said into another language in real time, so they are commonly used by hearing people as well. Computer-controlled orthotic devices have been introduced. These "walking machines" enable paraplegic persons to walk and climb stairs. The prosthetic devices are not yet usable by all paraplegic persons, as many physically disabled persons have dysfunctional joints from years of disuse. However, the advent of orthotic walking systems is providing more motivation to have these joints replaced. There is a growing perception that the primary disabilities of blindness, deafness, and physical impairment do not necessarily impart handicaps. Disabled persons routinely describe their disabilities as mere inconveniences. Intelligent technology has become the great leveler. (Kurzweil 139)

Prediction for 2019:

Blind persons routinely use eyeglass-mounted reading-navigation systems, which incorporate the new, digitally controlled, high-resolution optical sensors. These systems can read text in the real world, although since most print is now electronic, print-to-speech reading is less of a requirement. The navigation function of these systems, which emerged about ten years ago, is now perfected. These automated reading-navigation assistants communicate to blind users through both speech and tactile indicators. These systems are also widely used by sighted persons since they provide a high-resolution interpretation of the visual world. Retinal and vision neural implants have emerged but have limitations and are used by only a small percentage of blind persons. Deaf persons routinely read what other people are saying through the deaf persons' lens displays. There are systems that provide visual and tactile interpretations of other auditory experiences such as mus ic, but there is debate regarding the extent to which these systems provide an experience comparable to that of a hearing person. Cochlear and other implants for improving hearing are very effective and are widely used. Paraplegic and some quadriplegic persons routinely walk and climb stairs through a combination of computer- controlled nerve stimulation and exoskeletal robotic devices. Generally, disabilities such as blindness, deafness, and paraplegia are not noticeable and are not regarded as significant. (Kurzweil 145)

prediction for 2029:

The prevalence of highly intelligent visual navigation devices for the blind, speech-to-print display devices for the deaf, nerve stimulation, intelligent orthotic prosthetics for the physically disabled, and a variety of neural implant technologies has essentially eliminated the handicaps associated with most disabilities. Sensory-enhancement devices are in fact used by most of the population. (Kurzweil 162)

*** Disability: Definitions, Models, Experience in Stanfod Encyclopedia of Philosophy
https://plato.stanford.edu/entries/disability/#EpiMorAut

3.4
Such inclusiveness, however, requires an acceptance of diverse attitudes and opinions. Even if the majority of people we would classify as having disabilities perceived societal mistreatment and institutional barriers to be more oppressive than their diagnoses, not all of them would share that view or agree on the best response. African-Americans have different views about affirmative action, and many women do not believe that the option of legal abortion is essential for women's full participation in society. Disability theorists can find it frustrating that most nondisabled people in bioethics dispute their claims about their experience, but those theorists must respond to whatever challenge to the social model is posed by people with disabilities who see their condition, and not society, as the major impediment to their living rewarding lives. Many people with both congenital and acquired disabilities have said that they don't want cures but do want societal change, but that hardly warrants the charge that Christopher Reeve wasn't speaking from his experience of disability when he argued that what he wanted was “cure” and not social change (Johnson, 2003; Shakespeare, 2006).

** Morris
*** Pride Against Prejudice
 It took me a long time after my accident to feel good about being out in public with other disabled people. For me the breakthrough came when I was leaving a meeting in the company of a disabled man. As we came towards the doors leading out of the building a woman rushed up, saying, 'Let me open the doors for you' (her attitude of 'Poor things' written all over her face and oozing out of her voice). But, before she could push her way in front of us — as people trying to open doors do so often — the doors opened automatically. 'Oh!' she cried, 'Isn't that clever. How does it work?' `I don't know,' I said, 'I'm not an electrician.' And we sailed through the doors, leaving her open-mouthed and superfluous.  

Thinking about this incident afterwards I realised I felt a feeling of power which came from two sources — the feeling of solidarity with another disabled person at whom her pity was also directed, and the fact that, for once, the physical environment had been altered to suit people like me. The automatic doors meant that I did not have to accept help from someone whose help was offered on her terms and not mine. (Morris 30)

* proposal
Scholars such as David Doat have criticized transhumanism, an ideological stance and subculture advanced by technologists and futurists, especially those like Ray Kurzweil who have a connection to Silicon Valley. He and others have observed that transhumanists regard the disabled as rhetorical stepping stones who provide evidence of an essential incompleteness in humanity that must be overcome with technology. This allows transhumanists to assume the role of saviors, creating infrastructure for others while determining the boundaries of what is reasonable, achievable, and desirable.

I accept this critique of the transhuman ideology, yet in rejecting the role advocates of transhumanism have created for the disabled, I wish to advance a means of understanding personal relationships among the individual, technology, and society. Haccessibility is the creation of infrastructure, broadly construed, that enables individual self-determination within a world that is socially and technologically determined. If infrastructure comprises material and social circumstances, such as roads, housing, communications systems, organizations, laws, and resources, that determine what is practical and possible, then haccessibility is the creation of personal infrastructure that expands the boundaries of the possible in ways that are personal, small-scale, and resistant to larger forces. The term can apply to anyone, whether teenagers (mis)using mentions of promoted brands on Facebook to receive a signal boost from its algorithm or the business executive who uses his desktop computer as a footstool. However, the term is most significant for the disabled, since adaptations, workarounds, prosthetics, individualized skills, and acts of provocation and resistance are critical to their ability to survive and thrive in an able world. Beyond its tendency toward self-determination, another critical aspect of haccessibility is its indifference to propriety and the need or desire to "pass" in wider society. Like the old-school hackers from which the term is derived, those who practice haccessibility often violate boundaries in order to expand their capabilities, explore their environment, and play at the boundaries of the acceptable, the possible, and the expected.

This section will advocate for haccessibility as a means of understanding the multivalent intersections among individuals and their social and technological contexts. It will also provide examples of ways in which institutional morays, practices, and rules have been (and often must be) violated by disabled individuals in pursuit of their goals. This chapter will draw on works such as Donna Haraway's /Cyborg Manifesto/, Richard Stallman's /Free Software, Free Society/, and Scott Dexter and Samir Chopra's /Decoding Liberation/ in addition to foundational works in disability studies, especially those relating to post- and transhumanism. The chapter will also examine communities that have formed around the practice of hacking personal infrastructure, such as [[http://blarbl.blogspot.com/][Blind Arduino]], [[https://talkingarch.tk/][Talking Arch]], and [[https://www.seeingwithsound.com/android.htm][seeingwithsound]].

* links
https://mobile.nytimes.com/2017/11/05/sports/blind-marathoner-technology.html

self feeding device
https://www.youtube.com/watch?v=JnEK5fCGy1U






**** Library

*** Critical Making


*** Relationship of Negotiated Access to the Social Model
affect theory - provides a point of understanding between disabled and able communities
mention the data about obama's speeches and what's effective in turning people's mind away from hatred
social model is required to MAKE ROOM for negotiated access; games as an example, iOS, right to repair, DMCA

*** Relationship of Negotiated Access to the Medical Model




bird game
https://ifcomp.org/1758/content/10pm.html
https://medium.com/@lisaferris/of-little-faith-a-troubling-trend-with-blindness-professionals-1a6f2f85597c

toby documentary (playing doom)
https://www.youtube.com/watch?v=07jOSs7Fun8&feature=youtu.be&a=

# accessible game but not accessible platform
https://www.applevis.com/forum/macos-mac-app-discussion/using-steam-mac

accessible homestuck
http://accessiblehomestuckproject.tumblr.com/links

19th century disability archive
http://www.nineteenthcenturydisability.org/

list of books
http://www.nlcdd.org/resources-books-movies-disability.html

# made for my wheelchair
https://web.archive.org/web/20171118211851/https://makea.org/public/
http://madeformywheelchair.de/

# echolocation prosthetic
https://www.youtube.com/watch?v=DhHc1g0qG-8&lc=UgyKX0Xy0lhSSVBfsG14AaABAg


piet
[[http://www.archimedes-lab.org/grooks.html]]


affordances in the age of the inaffordable
the present is here, it's just not equally distrubuted

types of transhumanism
https://www.nytimes.com/2017/12/22/books/review/heavens-on-earth-michael-shermer.html?partner=rss&emc=rss
jeff note
I know I mentioned Giambattista Vico, who argues that the certainty of mathematics derives from the fact that we created it, which gives us an “inside” view of it.  Vico is a pretty difficult thinker to get into, but Isaiah Berlin’s essay on him is a good place to start.


vinyl audiobooks:
https://www.inc.com/wanda-thibodeaux/this-company-is-taking-a-totally-new-approach-to-audiobooks-heres-why-youll-love-it.html?cid=sf01001&sr_share=twitter


on doing stuff for yourself:
http://www.ctheory.net/articles.aspx?id=74

D&D accessible (has passage about 3D printed dice but they have raised edges, kind of thing a sighted person wouldn't think about)
https://unseen-beauty.com/2018/02/07/dd-for-blind-players/
http://madeformywheelchair.de/

Latex miosis
https://github.com/Submanifold/latex-mimosis
