* notes
transhumanists are regarded as suspicious because they wish to apply the cure

yet transhumanists don't want just to apply the cure to the disabled, they want to apply the cure to everyone

this essay argues that we should regard the able as part of disability studies because interactions between the individual and the environment are always negotiated

accessibility describes the space between an individual and a normative goal. hacking describes the space between an indivudual and a non-normative goal. 


transhumanists and the cure
we are all disabled, all is negotiation
hacking is exclusionary
hacking is inclusionary
we're already hackers, let's act like it
hacking as rhetoric
** The Needs of the Disabled Many

"Isn't it better not to be disabled?" The answer to this question is more complicated than it seems, and theanswer differs based on whether you're talking about 



XXX section on why I give a shit about this XXX

* quotes
** stallman interview
RMS: It means someone who enjoys playful cleverness, especially in programming but other media are also possible. In the 14th century, Guillaume de Machaut wrote a palindromic three-part musical composition. It sounded good, too—I think I played in it once, because I still remember one of the parts. I think that was a good hack. I heard somewhere that J. S. Bach did something similar.
One possible arena for playful cleverness is breaking security. Hackers never had much respect for bureaucratic restrictions. If the computer was sitting idle because the administrators wouldn't let them use it, they would sometimes figure out how to bypass the obstacles and use it anyway. If this required cleverness, it would be fun in itself, as well as making it possible to do other hacking (for instance, useful work) on the computer instead of twiddling one's thumbs. But not all hackers did security breaking. Many never were interested in that. 
[[https://www.gnu.org/philosophy/rms-hack.html][interview with richard stallman]]
** hackers
Peter Samson and his friends had grown up with a specific relationship to the world, wherein things had meaning only if you found out how they worked. And how would you go about that if not by getting your hands on them?

** kurzweil
*** spiritual machines
It is the applications of the technology benefiting disabled people that have brought me the greatest gratification. There is a fortuitous match between the capabilities of contemporary computers and the needs of a disabled person. We're not creating cybernetic geniuses today—not yet. The intelligence of our present-day intelligent computers is narrow, which can provide effective solutions for the narrow deficits of most disabled persons. The restricted intelligence of the machine works effectively with the broad and flexible intelligence of the disabled person. Overcoming the handicaps associated with disabilities using AI technologies has long been a personal goal of mine. With regard to the major physical and sensory disabilities, I believe that in a couple of decades we will come to herald the effective end of handicaps. As amplifiers of human thought, computers have great potential to assist human expression and to expand creativity for all of us. I hope to continue playing a role in harnessing this potential. (Kurzweil 128)

Deaf persons—or anyone with a hearing impairment—commonly use portable speech-to-text listening machines, which display a real-time transcription of what people are saying. The deaf user has the choice of either reading the transcribed speech as displayed text, or watching an animated person gesturing in sign language. These have eliminated the primary communication handicap associated with deafness. Listening machines can also translate what is being said into another language in real time, so they are commonly used by hearing people as well. Computer-controlled orthotic devices have been introduced. These "walking machines" enable paraplegic persons to walk and climb stairs. The prosthetic devices are not yet usable by all paraplegic persons, as many physically disabled persons have dysfunctional joints from years of disuse. However, the advent of orthotic walking systems is providing more motivation to have these joints replaced. There is a growing perception that the primary disabilities of blindness, deafness, and physical impairment do not necessarily impart handicaps. Disabled persons routinely describe their disabilities as mere inconveniences. Intelligent technology has become the great leveler. (Kurzweil 139)

Prediction for 2019:

Blind persons routinely use eyeglass-mounted reading-navigation systems, which incorporate the new, digitally controlled, high-resolution optical sensors. These systems can read text in the real world, although since most print is now electronic, print-to-speech reading is less of a requirement. The navigation function of these systems, which emerged about ten years ago, is now perfected. These automated reading-navigation assistants communicate to blind users through both speech and tactile indicators. These systems are also widely used by sighted persons since they provide a high-resolution interpretation of the visual world. Retinal and vision neural implants have emerged but have limitations and are used by only a small percentage of blind persons. Deaf persons routinely read what other people are saying through the deaf persons' lens displays. There are systems that provide visual and tactile interpretations of other auditory experiences such as mus ic, but there is debate regarding the extent to which these systems provide an experience comparable to that of a hearing person. Cochlear and other implants for improving hearing are very effective and are widely used. Paraplegic and some quadriplegic persons routinely walk and climb stairs through a combination of computer- controlled nerve stimulation and exoskeletal robotic devices. Generally, disabilities such as blindness, deafness, and paraplegia are not noticeable and are not regarded as significant. (Kurzweil 145)

prediction for 2029:

The prevalence of highly intelligent visual navigation devices for the blind, speech-to-print display devices for the deaf, nerve stimulation, intelligent orthotic prosthetics for the physically disabled, and a variety of neural implant technologies has essentially eliminated the handicaps associated with most disabilities. Sensory-enhancement devices are in fact used by most of the population. (Kurzweil 162)

*** Disability: Definitions, Models, Experience in Stanfod Encyclopedia of Philosophy
https://plato.stanford.edu/entries/disability/#EpiMorAut

3.4
Such inclusiveness, however, requires an acceptance of diverse attitudes and opinions. Even if the majority of people we would classify as having disabilities perceived societal mistreatment and institutional barriers to be more oppressive than their diagnoses, not all of them would share that view or agree on the best response. African-Americans have different views about affirmative action, and many women do not believe that the option of legal abortion is essential for women's full participation in society. Disability theorists can find it frustrating that most nondisabled people in bioethics dispute their claims about their experience, but those theorists must respond to whatever challenge to the social model is posed by people with disabilities who see their condition, and not society, as the major impediment to their living rewarding lives. Many people with both congenital and acquired disabilities have said that they don't want cures but do want societal change, but that hardly warrants the charge that Christopher Reeve wasn't speaking from his experience of disability when he argued that what he wanted was “cure” and not social change (Johnson, 2003; Shakespeare, 2006).

** Morris
*** Pride Against Prejudice
 It took me a long time after my accident to feel good about being out in public with other disabled people. For me the breakthrough came when I was leaving a meeting in the company of a disabled man. As we came towards the doors leading out of the building a woman rushed up, saying, 'Let me open the doors for you' (her attitude of 'Poor things' written all over her face and oozing out of her voice). But, before she could push her way in front of us — as people trying to open doors do so often — the doors opened automatically. 'Oh!' she cried, 'Isn't that clever. How does it work?' `I don't know,' I said, 'I'm not an electrician.' And we sailed through the doors, leaving her open-mouthed and superfluous.  

Thinking about this incident afterwards I realised I felt a feeling of power which came from two sources — the feeling of solidarity with another disabled person at whom her pity was also directed, and the fact that, for once, the physical environment had been altered to suit people like me. The automatic doors meant that I did not have to accept help from someone whose help was offered on her terms and not mine. (Morris 30)

* proposal
Scholars such as David Doat have criticized transhumanism, an ideological stance and subculture advanced by technologists and futurists, especially those like Ray Kurzweil who have a connection to Silicon Valley. He and others have observed that transhumanists regard the disabled as rhetorical stepping stones who provide evidence of an essential incompleteness in humanity that must be overcome with technology. This allows transhumanists to assume the role of saviors, creating infrastructure for others while determining the boundaries of what is reasonable, achievable, and desirable.

I accept this critique of the transhuman ideology, yet in rejecting the role advocates of transhumanism have created for the disabled, I wish to advance a means of understanding personal relationships among the individual, technology, and society. Haccessibility is the creation of infrastructure, broadly construed, that enables individual self-determination within a world that is socially and technologically determined. If infrastructure comprises material and social circumstances, such as roads, housing, communications systems, organizations, laws, and resources, that determine what is practical and possible, then haccessibility is the creation of personal infrastructure that expands the boundaries of the possible in ways that are personal, small-scale, and resistant to larger forces. The term can apply to anyone, whether teenagers (mis)using mentions of promoted brands on Facebook to receive a signal boost from its algorithm or the business executive who uses his desktop computer as a footstool. However, the term is most significant for the disabled, since adaptations, workarounds, prosthetics, individualized skills, and acts of provocation and resistance are critical to their ability to survive and thrive in an able world. Beyond its tendency toward self-determination, another critical aspect of haccessibility is its indifference to propriety and the need or desire to "pass" in wider society. Like the old-school hackers from which the term is derived, those who practice haccessibility often violate boundaries in order to expand their capabilities, explore their environment, and play at the boundaries of the acceptable, the possible, and the expected.

This section will advocate for haccessibility as a means of understanding the multivalent intersections among individuals and their social and technological contexts. It will also provide examples of ways in which institutional morays, practices, and rules have been (and often must be) violated by disabled individuals in pursuit of their goals. This chapter will draw on works such as Donna Haraway's /Cyborg Manifesto/, Richard Stallman's /Free Software, Free Society/, and Scott Dexter and Samir Chopra's /Decoding Liberation/ in addition to foundational works in disability studies, especially those relating to post- and transhumanism. The chapter will also examine communities that have formed around the practice of hacking personal infrastructure, such as [[http://blarbl.blogspot.com/][Blind Arduino]], [[https://talkingarch.tk/][Talking Arch]], and [[https://www.seeingwithsound.com/android.htm][seeingwithsound]].

* links
# boind marathoner
https://mobile.nytimes.com/2017/11/05/sports/blind-marathoner-technology.html

# self feeding device
https://www.youtube.com/watch?v=JnEK5fCGy1U

**** Library

*** Critical Making


*** Relationship of Negotiated Access to the Social Model
affect theory - provides a point of understanding between disabled and able communities
mention the data about obama's speeches and what's effective in turning people's mind away from hatred
social model is required to MAKE ROOM for negotiated access; games as an example, iOS, right to repair, DMCA

*** Relationship of Negotiated Access to the Medical Model




bird symbol game
https://ifcomp.org/1758/content/10pm.html
https://medium.com/@lisaferris/of-little-faith-a-troubling-trend-with-blindness-professionals-1a6f2f85597c

toby documentary (playing doom)
https://www.youtube.com/watch?v=07jOSs7Fun8&feature=youtu.be&a=

# accessible game but not accessible platform
https://www.applevis.com/forum/macos-mac-app-discussion/using-steam-mac

accessible homestuck
http://accessiblehomestuckproject.tumblr.com/links

19th century disability archive
http://www.nineteenthcenturydisability.org/

accoustic headbands
http://beckerexhibits.wustl.edu/did/19thcent/index.htm

list of books
http://www.nlcdd.org/resources-books-movies-disability.html

# made for my wheelchair
https://web.archive.org/web/20171118211851/https://makea.org/public/
http://madeformywheelchair.de/

# echolocation prosthetic
https://www.youtube.com/watch?v=DhHc1g0qG-8&lc=UgyKX0Xy0lhSSVBfsG14AaABAg


piet
[[http://www.archimedes-lab.org/grooks.html]]


affordances in the age of the inaffordable
the present is here, it's just not equally distrubuted

types of transhumanism
https://www.nytimes.com/2017/12/22/books/review/heavens-on-earth-michael-shermer.html?partner=rss&emc=rss
jeff note
I know I mentioned Giambattista Vico, who argues that the certainty of mathematics derives from the fact that we created it, which gives us an “inside” view of it.  Vico is a pretty difficult thinker to get into, but Isaiah Berlin’s essay on him is a good place to start.


vinyl audiobooks:
https://www.inc.com/wanda-thibodeaux/this-company-is-taking-a-totally-new-approach-to-audiobooks-heres-why-youll-love-it.html?cid=sf01001&sr_share=twitter


on doing stuff for yourself:
http://www.ctheory.net/articles.aspx?id=74

D&D accessible (has passage about 3D printed dice but they have raised edges, kind of thing a sighted person wouldn't think about)
https://unseen-beauty.com/2018/02/07/dd-for-blind-players/
http://madeformywheelchair.de/

Latex miosis
https://github.com/Submanifold/latex-mimosis






* Mossman, Mark. Acts of Becoming: Autobiography, Frankenstein, and the Postmodern Body
http://pmc.iath.virginia.edu/issue.501/11.3mossman.html


my life is a postmodern text


disabled english profesor, renal failure, writing about frakenstein. good shit. his body is a beach, that is, a point of intersection between an ocean of imposed identity and the land of escaping disabled discourses—normality. ultimatley argues that changes in society and changes in technology related to the capabilities of the body have opened a new space he calls the postmodern body

My body is a postmodern text. I am aware that I am constantly located in a social space, a gray area where the category of disability is manufactured. My body is deceptive, though, so I can at times escape, slip out of the net of discourses that determine the lives of so many disabled people. I am aware that I am able to have these moments because my body is so pliable in its ability to be normal and then abnormal and then normal again. I live in a space that allows perception, comprehensive awareness. I can feel the colonizing discourses of biomedical culture wash over my body like waves sweeping up onto the seashore. They recede and I am normal; they crash again and I am drowning in stereotype and imposed identity. The unique privilege of my life has been the fact that I am, figuratively, a beach, an edge of something; I know the different spheres of water and sand; I am able to live in both worlds. And as I move through these worlds, as the narrative of my life is constructed around and through me, I am aware of how I change and am changed, written and re-written by the different clusters of discourse that mark all of our lives: at the doctor's office last week, for example, I was "ill," a "patient"; on the basketball court later that day I was "healthy," a "player."


At the outset my question is, what happens when a disabled individual writes herself? What happens when the disabled person explains and articulates, through either writing or bodily practice, disability? There has been an increasing number of theorists and researchers working in the field of disability studies who have attempted to construct answers to these kinds of questions. In doing so, what critics often discover is a need to expand the emerging field itself. For example, in commenting on the importance of scholars in the humanities working in a field dominated by the social sciences, Lennard J. Davis asserts that narratives written by individuals who are disabled constitute important voices in the workings of culture at large and need, therefore, to be understood through a humanities-centered critical approach:


In this theoretical context, writing disability is the (re)production of disability, a potent act of creation. Autobiography by a disabled person is an authentication of lived, performed experience; it is a process of making, of being able to "translate knowing into telling" (White 1). Using the last two decades of criticism and theory as a map, disabled autobiography can be traced as a postmodern, postcolonial endeavor, for when disability writing constructs the particular self-definition it is attempting to narrate, it automatically resists repressive stereotype at large and attempts to reclaim ownership of the body and the way the body is understood. In other words, writing, autobiography, the narration of an experience by a disabled person to a reader or an immediate listener, enables a marginalized voice to be heard, which in turn causes cultural practice and stereotyped roles to change. The experiences rendered in "illness narratives," as Arthur Kleinmann has named them, work against any kind of essential universalism and instead attempt to demonstrate particularity and individuality in experience. The writing of illness and the writing of disability, and as David Morris has recently noted the two terms are often collapsed together in postmodern culture, involve new constructions of reality, new categories for the body's performance in cultural practice. Disabled autobiography is a conscious act of becoming.

 and superior in strength, in its ability to experience extremes in cold and heat, to wreck the inscribing process of outside definition. Being constructed in postmodern discourse, being the person I was and am, I read the creature as "powerful" in its resistance: the creature gained power through its disempowered body; it took the imposition of "abnormality" and used it as an articulation of strength and purpose. When I read the narrative, I read these terms into my own body; I used them to explain my own life.


Of course, as usual these feelings were almost immediately countered by another very different experience. On the first day back from that trip, I went to the dentist for a check-up. Having been out in the Florida sun, I had a tan, and as I sat down in the reclined dentist's chair, ready to be examined, he mentioned that I looked great and had a "healthy glow." I laughed, but what flashed across my mind was what I had actually experienced while I was getting this tan (which has now begun to peel): that is, disability, the constructions of illness. The dentist defined my body and, in turn, "me," as being "healthy." But just the day before at the pool I was certainly defined as "disabled." Any nephrologist will tell you that for the last three years I have been seriously "ill." My point here is simple: it is clear that the text of my body, which is my body, is profoundly unstable. Again and again I discover how I am both normal and abnormal, both able-bodied and healthy, and disabled and ill. As I will demonstrate, it is this profound discursive indeterminacy that defines the postmodern body and the direction that both body criticism and disability studies are taking as they develop.
s the polarization of normal and abnormal that the marketing of Jordan's body seems to establish. Elliott is able to be both extremes of the pole: he is ill and healthy; he is a body that is unnatural and a body that is strikingly natural. He is impaired and disabled and neither all at the same time. He is postmodern. Sean Elliott does not only "look back" at or make eye contact with the defining practices of culture and the stares of millions of people; he redefines himself in those moments, and he succeeds in the re-definition by making himself a viable option for the thre

With Sean Elliott's comeback, it is now widely apparent that the transplanted body too has this same indeterminacy inscribed upon it, built inside of it. The suggestion is, I think, that the person, any person, is a system of organs, almost all of which can be either replaced or relocated, depending on the immediate need. In this light, the body itself seems to break down as an absolute posit of selfhood and determinacy. What emerges is a sense of possibility. What emerges is the postmodern body.


https://longreads.com/2018/02/15/blockchain-just-isnt-as-radical-as-you-want-it-to-be/



* planned obsalesence

NINES as a project to avoid silos in the humanities (called "atomization")
The problem in developing such new forms of publication as these databases, however, is what Jerome McGann (2005, 112) has referred to as one of the crises facing the digital humanities: such “scholarship—even the best of it—is all more or less atomized”; the various digital texts and collections that have been created are “idiosyncratically designed and so can’t talk to each other,” and there are no authoritative, systemic, searchable bibliographies of these projects that enable scholars to find the digital objects they’d like to reuse.13 In response to these problems, McGann and the Applied Research in ’Patacriticism group at the University of Virginia began developing NINES, the Networked Infrastructure for Nineteenth-century Electronic Scholarship, as “a three-year undertaking initiated in 2003 . . . to establish an online environment for publishing peer-reviewed research in nineteenth-century British and American studies” (p. 116). NINES has since become an aggregator for peer-reviewed digital objects published in a range of venues. This project, which has received significant funding from the Mellon Foundation, was established as a means of averting atomization in the digital humanities, bringing separate projects into dialogue with one another. The NINES goals, as described on the site (“What Is NINES?”), are:


elsivier implicated in peer review rings
cate that it was not in spite of but rather due to the peer-review process that published studies of the anti-inflammatory drugs Celebra and Vioxx excluded data about those drugs’ potential for causing heart damage. See also the revelation on The Scientist that Elsevier published six fake journals (Grant 2009b), and that Merck paid the publisher “to produce several volumes of a publication that had the look of a peer-reviewed medical journal, but contained only reprinted or summarized articles—most of which presented data favorable to Merck products” (Grant 2009a). Perhaps more famously, in what has been referred to as “Climategate,” claims that peer review may have been manipulated in promoting work in climate science resulted in calls among scientists for reform of the review process (Pearce 2010); I thank Nick Mirzoeff (2010) for that referenc

* Firtzpatrick

And some of that has happened. The Open Library of the Humanities, notably, was founded by two humanities scholars who are working closely with the scholars who operate the journals under its umbrella.3 And, of course, MLA Commons is a platform developed by a scholar-governed society on which members are encouraged to develop and share new projects with the field in a wide variety of ways.

But there’s been comparatively slow uptake on this end of the open access spectrum, and it’s worth considering why. On the one hand, there is the fact that publishing requires work, and comparatively few scholars have the time or inclination required to move some of their “own” work aside in favor of working on publishing’s machinery, whether by building their own publications or supporting others through the publishing process. That sort of work isn’t, by and large, what we trained for, and perhaps more importantly, it isn’t the kind of thing for which we get credit.4

Even more, there is the question of prestige: scholars continue to publish in venues that have established imprimaturs, and in venues that they have no editorial hand in, because those two factors continue to be privileged by the various review mechanisms up the chain. Scholars need to persuade internal and external review committees that their work has been selected through an impartial, rigorous review process, and all the better if the name of the organization that runs that review process resonates. But of course publishing collectives are capable of being just as (if not more) rigorous, and scholarly associations like my own can provide not just an imprimatur for those collectives but also access to the many other members in the field that the collectives would likely want to reach.

http://blogs.lse.ac.uk/impactofsocialsciences/2015/10/21/opening-up-open-access-kathleen-fitzpatrick/

Opening Up Open Access: Moving beyond business models and towards cooperative, scholar-organized, open networks.


