* sort
   :notes:
sure anything like a standard user exists—it was created by companies like apple through persistent and
clever marketing to convince people they should identify as standard users. by contrast, in the ’70s, when
the computer was not yet very profitable and it was still a niche market item for tinkerers and the curious,
it was marketed in more philosophical terms. my favorite ad from that era is for logo, a learning-oriented
programming language. in an issue of byte magazine from 1982 you can find an ad that describes logo
as “a language for poets, scientists, and philosophers” (logo, 1982). incredible! at this time, computers
were more about learning and creativity—open-ended learning and creativity.
"as if"

bibliographystyle:apalike
bibliography:references.bib


https://blogs.technet.microsoft.com/machinelearning/2018/09/10/why-would-prosthetic-arms-need-to-see-or-connect-to-cloud-ai/




techne


# alan k saying that the problem of access isn't actual
# access, but that people don't or can't use the access
# see 15:00
https://www.youtube.com/watch?v=t2l2t-d3tda


# destruction of fan-made project by copyright
https://torrentfreak.com/cbs-shuts-down-stage-9-a-fan-made-recreation-of-the-uss-enterprise-180927/




# cpap hacker
https://motherboard.vice.com/en_us/article/xwjd4w/im-possibly-alive-because-it-exists-why-sleep-apnea-patients-rely-on-a-cpap-machine-hacker


# computer bums
# emacs commune
# hacker idyll
http://www.oreilly.com/openbook/freedom/ch06.html


sousveillance
https://en.wikipedia.org/wiki/sousveillance

# whole earth catalog
https://www.newyorker.com/news/letter-from-silicon-valley/the-complicated-legacy-of-stewart-brands-whole-earth-catalog





# lego prosthetic
https://www.abc.net.au/news/2019-02-08/lego-prosthetic-arm-made-by-man-missing-limb/10792598

# hypersane
https://aeon.co/ideas/the-hypersane-are-among-us-if-only-we-are-prepared-to-look


# is literature against us?

https://nfb.org/sites/www.nfb.org/files/images/nfb/publications/convent/banque74.htm


# hypersane, good for final chapter
https://aeon.co/ideas/the-hypersane-are-among-us-if-only-we-are-prepared-to-look

:end:





* notes
to be a machine : adventures among cyborgs, utopians, hackers, and the futurists solving the modest problem of death
author
“We demonstrated that the Web had failed instead of served humanity, as it was supposed to have done, and failed in many places,” he told me. The increasing centralization of the Web, he says, has “ended up producing—with no deliberate action of the people who designed the platform—a large-scale emergent phenomenon which is anti-human.”
https://www.vanityfair.com/news/2018/07/the-man-who-created-the-world-wide-web-has-some-regrets


transhumanists are regarded as suspicious because they wish to apply the cure

yet transhumanists don't want just to apply the cure to the disabled, they want to apply the cure to everyone

this essay argues that we should regard the able as part of disability studies because interactions between the individual and the environment are always negotiated

accessibility describes the space between an individual and a normative goal. Hacking describes the space between an indivudual and a non-normative goal. 


transhumanists and the cure
we are all disabled, all is negotiation
hacking is exclusionary
hacking is inclusionary
we're already hackers, let's act like it
hacking as rhetoric
** Mossman, Mark. Acts of Becoming: Autobiography, Frankenstein, and the Postmodern Body
http://pmc.iath.virginia.edu/issue.501/11.3mossman.html


my life is a postmodern text


disabled english profesor, renal failure, writing about frakenstein. good shit. his body is a beach, that is, a point of intersection between an ocean of imposed identity and the land of escaping disabled discourses—normality. ultimatley argues that changes in society and changes in technology related to the capabilities of the body have opened a new space he calls the postmodern body

My body is a postmodern text. I am aware that I am constantly located in a social space, a gray area where the category of disability is manufactured. My body is deceptive, though, so I can at times escape, slip out of the net of discourses that determine the lives of so many disabled people. I am aware that I am able to have these moments because my body is so pliable in its ability to be normal and then abnormal and then normal again. I live in a space that allows perception, comprehensive awareness. I can feel the colonizing discourses of biomedical culture wash over my body like waves sweeping up onto the seashore. They recede and I am normal; they crash again and I am drowning in stereotype and imposed identity. The unique privilege of my life has been the fact that I am, figuratively, a beach, an edge of something; I know the different spheres of water and sand; I am able to live in both worlds. And as I move through these worlds, as the narrative of my life is constructed around and through me, I am aware of how I change and am changed, written and re-written by the different clusters of discourse that mark all of our lives: at the doctor's office last week, for example, I was "ill," a "patient"; on the basketball court later that day I was "healthy," a "player."


At the outset my question is, what happens when a disabled individual writes herself? What happens when the disabled person explains and articulates, through either writing or bodily practice, disability? There has been an increasing number of theorists and researchers working in the field of disability studies who have attempted to construct answers to these kinds of questions. In doing so, what critics often discover is a need to expand the emerging field itself. For example, in commenting on the importance of scholars in the humanities working in a field dominated by the social sciences, Lennard J. Davis asserts that narratives written by individuals who are disabled constitute important voices in the workings of culture at large and need, therefore, to be understood through a humanities-centered critical approach:


In this theoretical context, writing disability is the (re)production of disability, a potent act of creation. Autobiography by a disabled person is an authentication of lived, performed experience; it is a process of making, of being able to "translate knowing into telling" (White 1). Using the last two decades of criticism and theory as a map, disabled autobiography can be traced as a postmodern, postcolonial endeavor, for when disability writing constructs the particular self-definition it is attempting to narrate, it automatically resists repressive stereotype at large and attempts to reclaim ownership of the body and the way the body is understood. In other words, writing, autobiography, the narration of an experience by a disabled person to a reader or an immediate listener, enables a marginalized voice to be heard, which in turn causes cultural practice and stereotyped roles to change. The experiences rendered in "illness narratives," as Arthur Kleinmann has named them, work against any kind of essential universalism and instead attempt to demonstrate particularity and individuality in experience. The writing of illness and the writing of disability, and as David Morris has recently noted the two terms are often collapsed together in postmodern culture, involve new constructions of reality, new categories for the body's performance in cultural practice. Disabled autobiography is a conscious act of becoming.

 and superior in strength, in its ability to experience extremes in cold and heat, to wreck the inscribing process of outside definition. Being constructed in postmodern discourse, being the person I was and am, I read the creature as "powerful" in its resistance: the creature gained power through its disempowered body; it took the imposition of "abnormality" and used it as an articulation of strength and purpose. When I read the narrative, I read these terms into my own body; I used them to explain my own life.


Of course, as usual these feelings were almost immediately countered by another very different experience. On the first day back from that trip, I went to the dentist for a check-up. Having been out in the Florida sun, I had a tan, and as I sat down in the reclined dentist's chair, ready to be examined, he mentioned that I looked great and had a "healthy glow." I laughed, but what flashed across my mind was what I had actually experienced while I was getting this tan (which has now begun to peel): that is, disability, the constructions of illness. The dentist defined my body and, in turn, "me," as being "healthy." But just the day before at the pool I was certainly defined as "disabled." Any nephrologist will tell you that for the last three years I have been seriously "ill." My point here is simple: it is clear that the text of my body, which is my body, is profoundly unstable. Again and again I discover how I am both normal and abnormal, both able-bodied and healthy, and disabled and ill. As I will demonstrate, it is this profound discursive indeterminacy that defines the postmodern body and the direction that both body criticism and disability studies are taking as they develop.
s the polarization of normal and abnormal that the marketing of Jordan's body seems to establish. Elliott is able to be both extremes of the pole: he is ill and healthy; he is a body that is unnatural and a body that is strikingly natural. He is impaired and disabled and neither all at the same time. He is postmodern. Sean Elliott does not only "look back" at or make eye contact with the defining practices of culture and the stares of millions of people; he redefines himself in those moments, and he succeeds in the re-definition by making himself a viable option for the thre

With Sean Elliott's comeback, it is now widely apparent that the transplanted body too has this same indeterminacy inscribed upon it, built inside of it. The suggestion is, I think, that the person, any person, is a system of organs, almost all of which can be either replaced or relocated, depending on the immediate need. In this light, the body itself seems to break down as an absolute posit of selfhood and determinacy. What emerges is a sense of possibility. What emerges is the postmodern body.

** The Needs of the Disabled Many

"Isn't it better not to be disabled?" The answer to this question is more complicated than it seems, and theanswer differs based on whether you're talking about 



XXX section on why I give a shit about this XXX

* quotes
** The Myth of the machine

his thesis is to say that culture, other qualities of people are more important than technics for human development

-----

In terms of the currently accepted picture of the relation of man to technics, our age is passing from the primeval state of man, marked by his invention of tools and weapons for the purpose of achieving mastery over the forces of nature, to a radically different condition, in which he will have not only conquered nature, but detached himself as far as possible from the organic habitat.

With this new 'megatechnics' the dominant minority will create a uniform, all-enveloping, super-planetary structure, designed for automatic operation. Instead of functioning actively as an autonomous personality, man will become a passive, purposeless, machine-conditioned animal whose proper functions, as technicians now interpret man's role, will either be fed into the machine or strictly limited and controlled for the benefit of de-personalized, collective organizations.

-----

In this process of self-discovery and self-transformation, tools, in the narrow sense, served well as subsidiary instruments, but not as the main operative agent in man's development; for technics has never till our own age dissociated itself from the larger cultural whole in which man, as man, has always functioned. The classic Greek term 'tekhne' characteristically makes no distinction between industrial production and 'fine' or symbolic art; and for the greater part of human history these aspects were inseparable, one side respecting the objective conditions and functions, the other responding to subjective needs.

-----

The irrational factors that have sometimes constructively prompted, yet too often distorted, man's further development became plain at the moment when the formative elements in paleolithic and neolithic cultures united in the great cultural implosion that took place around the Fourth Millennium B.C.: what is usually called 'the rise of civilization.' The remarkable fact about this transformation technically is that it was the result, not of mechanical inventions, but of a radically new type of social organization: a product of myth, magic, religion, and the nascent science of astronomy. This implosion of sacred political powers and technological facilities cannot be accounted for by any inventory of the tools, the simple machines, and the technical processes then available. Neither the wheeled wagon, the plow, the potter's wheel, nor the military chariot could of themselves have accomplished the mighty transformations that took place in the great valleys of Egypt, Mesopotamia, and India, and eventually passed, in ripples and waves, to other parts of the planet.

The study of the Pyramid Age I made in preparation for writing 'The City in History' unexpectedly revealed that a close parallel existed between the first authoritarian civilizations in the Near East and our own, though most of our contemporaries still regard modern technics, not only as the highest point in man's intellectual development, but as an entirely new phenomenon. On the contrary, I found that what economists lately termed the Machine Age or the Power Age, had its origin, not in the so-called Industrial Revolution of the eighteenth century, but at the very outset in the organization of an archetypal machine composed of human parts.

Two things must be noted about this new mechanism, because they identify it throughout its historic course down to the present. The first is that the organizers of the machine derived their power and authority from a heavenly source. Cosmic order was the basis of this new human order. The exactitude in measurement, the abstract mechanical system, the compulsive regularity of this 'megamachine,' as I shall call it, sprang directly from astronomical observations and scientific calculations. This inflexible, predictable order, incorporated later in the calendar, was transferred to the regimentation of the human components. As against earlier forms of ritualized order, this mechanized order was external to man. By a combination of divine command and ruthless military coercion, a large population was made to endure grinding poverty and forced labor at mind-dulling repetitive tasks in order to insure "Life, Prosperity, and Health" for the divine or semi-divine ruler and his entourage.

The second point is that the grave social defects of the human machine were partly offset by its superb achievements in flood control and grain production, which laid the ground for an enlarged achievement in every area of human culture: in monumental art, in codified law, in systematically pursued and permanently recorded thought, in the augmentation of all the potentialities of the mind by the assemblage of a varied population, with diverse regional and vocational backgrounds in urban ceremonial centers. Such order, such collective security and abundance, such stimulating cultural mixtures were first achieved in Mesopotamia and Egypt, and later in India, China, Persia, and in the Andean and Mayan cultures: and they were never surpassed until the megamachine was reconstituted in a new form in our own time. Unfortunately these cultural advances were largely offset by equally great social regressions.












** One-Dimensional Man by Herbert Marcuse
introduction----------
By the 1950s, Marcuse thus perceived that the unparalleled affluence of the consumer society and the apparatus of planning and management in advanced capitalism had produced new forms of social administration and a "society without oppo- sition" that threatened individuality and that closed off possi- bilities of radical social change. In studies of the 1950s, he began sketching out a theory of a new type of technological society which would receive its fullest development in One-Dimensional Man. Marcuse's analysis is based on a conception of the historical rise of a technological world which overpowers and controls its subjects. In this technological world, Marcuse claims that meta- physics is superseded by technology, in that the previous metaphysical concept of subjectivity, which postulates an active subject confronting a controllable world of objects, is replaced by a one-dimensional technical world where "pure instru- mentality" and "efficacy" of arranging means and ends within a pre-established universe is the "common principle of thought
----------end introduction quotes

** stallman interview
RMS: It means someone who enjoys playful cleverness, especially in programming but other media are also possible. In the 14th century, Guillaume de Machaut wrote a palindromic three-part musical composition. It sounded good, too—I think I played in it once, because I still remember one of the parts. I think that was a good hack. I heard somewhere that J. S. Bach did something similar.
One possible arena for playful cleverness is breaking security. Hackers never had much respect for bureaucratic restrictions. If the computer was sitting idle because the administrators wouldn't let them use it, they would sometimes figure out how to bypass the obstacles and use it anyway. If this required cleverness, it would be fun in itself, as well as making it possible to do other hacking (for instance, useful work) on the computer instead of twiddling one's thumbs. But not all hackers did security breaking. Many never were interested in that. 
[[https://www.gnu.org/philosophy/rms-hack.html][interview with richard stallman]]
** hackers
Peter Samson and his friends had grown up with a specific relationship to the world, wherein things had meaning only if you found out how they worked. And how would you go about that if not by getting your hands on them?

** kurzweil

*** The disability rights movement: From charity to confrontation
 (hacessibility in a lab)
---155---

Accessible Classrooms and
Laboratories
Exhibiting a resourcefulness reminiscent of
Hotchkiss's ingenuity, mechanical engineer
Ira Cochin of the New Jersey Institute of
Technology and biologist Ben Van Wagner
of Fresno Pacific College created innova-
tive classrooms and laboratories. 26 In I977
Cochin, who was blind and later became
deaf, devised instruments-in what he called
the Macrolab-so that people with sen-
sory and speech impairments could be inte-
grated with nondisabled people in schools
and industry. For example, Cochin con-
nected an oscilloscope to a microphone so
that deaf (as well as hearing) students lit-
erally could see how frequencies changed
by viewing sound waves on a screen. With
Cochin's instruments, blind people-by in-
terpreting sound-were able to determine
the chemical constituents of a product, us-
ing a modified spectrometer, and to accu-
rately measure weights up to a milligram,
using a precision balance scale. Referring to


---156---

the "designing" of an early speech synthe-
sizer at the lab, William Skawinski, blind
chemist at the New Jersey Institute of Tech-
nology who directed the Macrolab, indi-
cated that the key to the program was that
the students served were involved in the
development of all of these instruments.
After his own careful research and much
medical consultation, Ben Van Wagner cre-
ated an environment that no longer precip-
itated "sick-building syndrome." Van Wag-
ner, a professor of science education, de-
scribes how he felt when he was diagnosed
with multiple chemical sensitivity: "The tox-
ins of the synthetic I990S had finally weak-
ened my immune system," Van Wagner ob-
serves, for "I was suffering from extreme
fatigue, lightheadedness, and arthritis so
bad that I could barely walk." Van Wagner
feared that since he had become allergic to
formaldehyde, he might not be able to go
on teaching.
Still undaunted, Van Wagner persisted in
his probing and ultimately discovered the
solutions that he was seeking:
I have adapted my zoology courses so as to use
alternative dissection materials from the local
fish market, non-formaldehyde substitute
specimens and computer technology ....
My college has ... allowed me to establish
a new "toxin-free" classroom outside of the
official science building and has provided me
with an excellent office with a window that
opens, which frees me from my ... air-tight
office .... As I continue to research the issue
of Environmental Illness, it is apparent that
it is a significant problem for many students
and adults.
People with disabilities, including those
with sensory and speech impairments and
multiple chemical sensitivity, can be suc-
cessful students and employees when they
are afforded appropriate, reasonable accom-
modations.
*** spiritual machines
It is the applications of the technology benefiting disabled people that have brought me the greatest gratification. There is a fortuitous match between the capabilities of contemporary computers and the needs of a disabled person. We're not creating cybernetic geniuses today—not yet. The intelligence of our present-day intelligent computers is narrow, which can provide effective solutions for the narrow deficits of most disabled persons. The restricted intelligence of the machine works effectively with the broad and flexible intelligence of the disabled person. Overcoming the handicaps associated with disabilities using AI technologies has long been a personal goal of mine. With regard to the major physical and sensory disabilities, I believe that in a couple of decades we will come to herald the effective end of handicaps. As amplifiers of human thought, computers have great potential to assist human expression and to expand creativity for all of us. I hope to continue playing a role in harnessing this potential. (Kurzweil 128)

Deaf persons—or anyone with a hearing impairment—commonly use portable speech-to-text listening machines, which display a real-time transcription of what people are saying. The deaf user has the choice of either reading the transcribed speech as displayed text, or watching an animated person gesturing in sign language. These have eliminated the primary communication handicap associated with deafness. Listening machines can also translate what is being said into another language in real time, so they are commonly used by hearing people as well. Computer-controlled orthotic devices have been introduced. These "walking machines" enable paraplegic persons to walk and climb stairs. The prosthetic devices are not yet usable by all paraplegic persons, as many physically disabled persons have dysfunctional joints from years of disuse. However, the advent of orthotic walking systems is providing more motivation to have these joints replaced. There is a growing perception that the primary disabilities of blindness, deafness, and physical impairment do not necessarily impart handicaps. Disabled persons routinely describe their disabilities as mere inconveniences. Intelligent technology has become the great leveler. (Kurzweil 139)

Prediction for 2019:

Blind persons routinely use eyeglass-mounted reading-navigation systems, which incorporate the new, digitally controlled, high-resolution optical sensors. These systems can read text in the real world, although since most print is now electronic, print-to-speech reading is less of a requirement. The navigation function of these systems, which emerged about ten years ago, is now perfected. These automated reading-navigation assistants communicate to blind users through both speech and tactile indicators. These systems are also widely used by sighted persons since they provide a high-resolution interpretation of the visual world. Retinal and vision neural implants have emerged but have limitations and are used by only a small percentage of blind persons. Deaf persons routinely read what other people are saying through the deaf persons' lens displays. There are systems that provide visual and tactile interpretations of other auditory experiences such as mus ic, but there is debate regarding the extent to which these systems provide an experience comparable to that of a hearing person. Cochlear and other implants for improving hearing are very effective and are widely used. Paraplegic and some quadriplegic persons routinely walk and climb stairs through a combination of computer- controlled nerve stimulation and exoskeletal robotic devices. Generally, disabilities such as blindness, deafness, and paraplegia are not noticeable and are not regarded as significant. (Kurzweil 145)

prediction for 2029:

The prevalence of highly intelligent visual navigation devices for the blind, speech-to-print display devices for the deaf, nerve stimulation, intelligent orthotic prosthetics for the physically disabled, and a variety of neural implant technologies has essentially eliminated the handicaps associated with most disabilities. Sensory-enhancement devices are in fact used by most of the population. (Kurzweil 162)

*** Disability: Definitions, Models, Experience in Stanfod Encyclopedia of Philosophy
https://plato.stanford.edu/entries/disability/#EpiMorAut

3.4
Such inclusiveness, however, requires an acceptance of diverse attitudes and opinions. Even if the majority of people we would classify as having disabilities perceived societal mistreatment and institutional barriers to be more oppressive than their diagnoses, not all of them would share that view or agree on the best response. African-Americans have different views about affirmative action, and many women do not believe that the option of legal abortion is essential for women's full participation in society. Disability theorists can find it frustrating that most nondisabled people in bioethics dispute their claims about their experience, but those theorists must respond to whatever challenge to the social model is posed by people with disabilities who see their condition, and not society, as the major impediment to their living rewarding lives. Many people with both congenital and acquired disabilities have said that they don't want cures but do want societal change, but that hardly warrants the charge that Christopher Reeve wasn't speaking from his experience of disability when he argued that what he wanted was “cure” and not social change (Johnson, 2003; Shakespeare, 2006).

** Morris
*** Pride Against Prejudice
 It took me a long time after my accident to feel good about being out in public with other disabled people. For me the breakthrough came when I was leaving a meeting in the company of a disabled man. As we came towards the doors leading out of the building a woman rushed up, saying, 'Let me open the doors for you' (her attitude of 'Poor things' written all over her face and oozing out of her voice). But, before she could push her way in front of us — as people trying to open doors do so often — the doors opened automatically. 'Oh!' she cried, 'Isn't that clever. How does it work?' `I don't know,' I said, 'I'm not an electrician.' And we sailed through the doors, leaving her open-mouthed and superfluous.  

Thinking about this incident afterwards I realised I felt a feeling of power which came from two sources — the feeling of solidarity with another disabled person at whom her pity was also directed, and the fact that, for once, the physical environment had been altered to suit people like me. The automatic doors meant that I did not have to accept help from someone whose help was offered on her terms and not mine. (Morris 30)



** Medeval Tecnology and Social Change
As our understanding of the history of technology increases, it becomes clear that a new device merely opens a door; it does not compel one to enter. The acceptance or rejection of an invention, or the extent to which its implications are realized if it is accepted, depends quite as much upon the condition of a society, and upon the imagination of its leaders, as upon the nature of the technological item itself. As we shall see, the Anglo—Saxons used the stirrup, but did not comprehend it; and for this they paid a fearful price. While semi-feudal relationships and institutions had long been scattered thickly over the civilized world, it was the Franks alone—presumably led by Charles Martel’s genius—who fully grasped the possibilities inherent in the stirrup and created in terms of it a new type of warfare supported by a novel structure of society which we call (28)
* proposal
Scholars such as David Doat have criticized transhumanism, an ideological stance and subculture advanced by technologists and futurists, especially those like Ray Kurzweil who have a connection to Silicon Valley. He and others have observed that transhumanists regard the disabled as rhetorical stepping stones who provide evidence of an essential incompleteness in humanity that must be overcome with technology. This allows transhumanists to assume the role of saviors, creating infrastructure for others while determining the boundaries of what is reasonable, achievable, and desirable.

I accept this critique of the transhuman ideology, yet in rejecting the role advocates of transhumanism have created for the disabled, I wish to advance a means of understanding personal relationships among the individual, technology, and society. Haccessibility is the creation of infrastructure, broadly construed, that enables individual self-determination within a world that is socially and technologically determined. If infrastructure comprises material and social circumstances, such as roads, housing, communications systems, organizations, laws, and resources, that determine what is practical and possible, then haccessibility is the creation of personal infrastructure that expands the boundaries of the possible in ways that are personal, small-scale, and resistant to larger forces. The term can apply to anyone, whether teenagers (mis)using mentions of promoted brands on Facebook to receive a signal boost from its algorithm or the business executive who uses his desktop computer as a footstool. However, the term is most significant for the disabled, since adaptations, workarounds, prosthetics, individualized skills, and acts of provocation and resistance are critical to their ability to survive and thrive in an able world. Beyond its tendency toward self-determination, another critical aspect of haccessibility is its indifference to propriety and the need or desire to "pass" in wider society. Like the old-school hackers from which the term is derived, those who practice haccessibility often violate boundaries in order to expand their capabilities, explore their environment, and play at the boundaries of the acceptable, the possible, and the expected.

This section will advocate for haccessibility as a means of understanding the multivalent intersections among individuals and their social and technological contexts. It will also provide examples of ways in which institutional morays, practices, and rules have been (and often must be) violated by disabled individuals in pursuit of their goals. This chapter will draw on works such as Donna Haraway's /Cyborg Manifesto/, Richard Stallman's /Free Software, Free Society/, and Scott Dexter and Samir Chopra's /Decoding Liberation/ in addition to foundational works in disability studies, especially those relating to post- and transhumanism. The chapter will also examine communities that have formed around the practice of hacking personal infrastructure, such as [[http://blarbl.blogspot.com/][Blind Arduino]], [[https://talkingarch.tk/][Talking Arch]], and [[https://www.seeingwithsound.com/android.htm][seeingwithsound]].

* links

# Why saying everone has a disability is a lie
https://crippledscholar.com/2015/03/02/why-saying-everyone-has-some-kind-of-disability-is-a-lie/


# gaia hypothesis bruno lateur
https://lareviewofbooks.org/article/bruno-latour-tracks-down-gaia/#!


# diable 3 blind gamer
http://www.brandoncole.net/?p=261

# blind lightsaber + fan representation 
https://blackgirlnerds.com/fan-interpretation-matters/

# blind marathoner
https://mobile.nytimes.com/2017/11/05/sports/blind-marathoner-technology.html

# self feeding device
https://www.youtube.com/watch?v=JnEK5fCGy1U

bird symbol game
https://ifcomp.org/1758/content/10pm.html
https://medium.com/@lisaferris/of-little-faith-a-troubling-trend-with-blindness-professionals-1a6f2f85597c

toby documentary (playing doom)
https://www.youtube.com/watch?v=07jOSs7Fun8&feature=youtu.be&a=

# accessible game but not accessible platform
https://www.applevis.com/forum/macos-mac-app-discussion/using-steam-mac

accessible homestuck
http://accessiblehomestuckproject.tumblr.com/links
https://longreads.com/2018/02/15/blockchain-just-isnt-as-radical-as-you-want-it-to-be/

--

19th century disability archive
http://www.nineteenthcenturydisability.org/

accoustic headbands
http://beckerexhibits.wustl.edu/did/19thcent/index.htm

list of books
http://www.nlcdd.org/resources-books-movies-disability.html

# made for my wheelchair
https://web.archive.org/web/20171118211851/https://makea.org/public/
http://madeformywheelchair.de/

# echolocation prosthetic
https://www.youtube.com/watch?v=DhHc1g0qG-8&lc=UgyKX0Xy0lhSSVBfsG14AaABAg


piet
[[http://www.archimedes-lab.org/grooks.html]]


affordances in the age of the inaffordable
the present is here, it's just not equally distrubuted

types of transhumanism
https://www.nytimes.com/2017/12/22/books/review/heavens-on-earth-michael-shermer.html?partner=rss&emc=rss
jeff note
I know I mentioned Giambattista Vico, who argues that the certainty of mathematics derives from the fact that we created it, which gives us an “inside” view of it.  Vico is a pretty difficult thinker to get into, but Isaiah Berlin’s essay on him is a good place to start.


vinyl audiobooks:
https://www.inc.com/wanda-thibodeaux/this-company-is-taking-a-totally-new-approach-to-audiobooks-heres-why-youll-love-it.html?cid=sf01001&sr_share=twitter


on doing stuff for yourself:
http://www.ctheory.net/articles.aspx?id=74

D&D accessible (has passage about 3D printed dice but they have raised edges, kind of thing a sighted person wouldn't think about)
https://unseen-beauty.com/2018/02/07/dd-for-blind-players/
http://madeformywheelchair.de/

Latex miosis
https://github.com/Submanifold/latex-mimosis




*** Critical Making


*** Relationship of Negotiated Access to the Social Model
affect theory - provides a point of understanding between disabled and able communities
mention the data about obama's speeches and what's effective in turning people's mind away from hatred
social model is required to MAKE ROOM for negotiated access; games as an example, iOS, right to repair, DMCA

*** Relationship of Negotiated Access to the Medical Model







* planned Obselescence

NINES as a project to avoid silos in the humanities (called "atomization")
The problem in developing such new forms of publication as these databases, however, is what Jerome McGann (2005, 112) has referred to as one of the crises facing the digital humanities: such “scholarship—even the best of it—is all more or less atomized”; the various digital texts and collections that have been created are “idiosyncratically designed and so can’t talk to each other,” and there are no authoritative, systemic, searchable bibliographies of these projects that enable scholars to find the digital objects they’d like to reuse.13 In response to these problems, McGann and the Applied Research in ’Patacriticism group at the University of Virginia began developing NINES, the Networked Infrastructure for Nineteenth-century Electronic Scholarship, as “a three-year undertaking initiated in 2003 . . . to establish an online environment for publishing peer-reviewed research in nineteenth-century British and American studies” (p. 116). NINES has since become an aggregator for peer-reviewed digital objects published in a range of venues. This project, which has received significant funding from the Mellon Foundation, was established as a means of averting atomization in the digital humanities, bringing separate projects into dialogue with one another. The NINES goals, as described on the site (“What Is NINES?”), are:


elsivier implicated in peer review rings
cate that it was not in spite of but rather due to the peer-review process that published studies of the anti-inflammatory drugs Celebra and Vioxx excluded data about those drugs’ potential for causing heart damage. See also the revelation on The Scientist that Elsevier published six fake journals (Grant 2009b), and that Merck paid the publisher “to produce several volumes of a publication that had the look of a peer-reviewed medical journal, but contained only reprinted or summarized articles—most of which presented data favorable to Merck products” (Grant 2009a). Perhaps more famously, in what has been referred to as “Climategate,” claims that peer review may have been manipulated in promoting work in climate science resulted in calls among scientists for reform of the review process (Pearce 2010); I thank Nick Mirzoeff (2010) for that referenc

* High Techne
Even when the debate concerns technological change, the terms of the debate do not seem to change at all: technology—or some aspect of it—is either celebrated or decried, cast as utopian or dystopian, in terms of its capacity either to serve “humanity” or to threaten it. The repetitiveness of these arguments results from the fact that they take the definition of tech- nology for granted. For all the discussion of the implications of techno- logical change, remarkably little attention has been devoted to possible changes in the conception of technology. (2)

draws attention to the idea that "high tech" serves as a distinguishing factor between haves and have nots...high tech is tech that we don't have access to

To speak of a high-tech aesthetic or style is not, then, simply to speak of a particular look or style, but of a cultural concern with “stylishness,” with “aesthetics,” that is intrinsic to high tech. Indeed, high tech is by defi- nition a technology that is “at the state of the art in terms of . . . function and design.” 6 To be “at the state of the art” implies not only a certain up-to-the-second currency, an attention to the latest technological devel- opments, but also a sense that both “function and design” have become elements in an aesthetic process or movement. As state-of-the-art tech- nology, high tech comes to be defined by its status as the “cutting edge” or “leading wave” of this technological aesthetic or style. Indeed, it is no coincidence that the often overblown rhetoric associated with high tech is reminiscent of the manifestos and slogans of the avant-garde artistic movements of the early twentieth century. High tech is, in fact, often pre- sented as a kind of avant-garde movement. (5)

Moreover, the very fact that metaphors such as “state of the art” and “avant-garde” have been so commonly employed— and accepted—in describing high tech is evidence that an “aesthetic” di- mension has become part of the definition of contemporary technology. Technology has come increasingly to be seen as a matter of aesthetics or style, as an “aesthetic movement.” Given this “aesthetic” aspect, the con- cept of technology in high tech might well be thought of as a kind of high techne ̄ —analogous to, though certainly quite different from, the Greek notion of techne. (5)


* Techne in Aristole's Ethics
relation to models supplied by the technai – variously translatable as ‘crafts’, ‘skills’, ‘arts’ or ‘forms of expertise’. (1)

From etymology and early usage, then, we can determine a property of techneˉ that will remain more or less constant: namely, that whoever practises a particular techneˉ possesses a determinate form of expertise. As Felix Heini- mann affi rms, ‘Each techneˉ is correlated with a quite determinate [bestim- mte] task and type of achievement’ (106). Or as Rudolf Löbl puts it, for every techneˉ ‘there is a telos, a goal, at which it aims . . . a kind of job [Werk] or action, that has to be realised’ (211). These references to particular ‘tasks’ or ‘goals’ should not be taken to preclude an individual techneˉ having as its proper concern a plurality of actions or products. After all, smithing (for one) encompasses a diverse set of these. Rather, the unique- ness of each techneˉ lies at the level of a particular range of tasks and aims: for example, geoˉrgia aims at the production of food, grammatikeˉ at both studying and teaching spelling and grammar, and mantikeˉ at predicting the future in various ways. It is in this sense, I take it, that ‘every techneˉ must have a quite determinate goal [Ziel], which distinguishes it from other technai’



* Fitzpatrick

And some of that has happened. The Open Library of the Humanities, notably, was founded by two humanities scholars who are working closely with the scholars who operate the journals under its umbrella.3 And, of course, MLA Commons is a platform developed by a scholar-governed society on which members are encouraged to develop and share new projects with the field in a wide variety of ways.

But there’s been comparatively slow uptake on this end of the open access spectrum, and it’s worth considering why. On the one hand, there is the fact that publishing requires work, and comparatively few scholars have the time or inclination required to move some of their “own” work aside in favor of working on publishing’s machinery, whether by building their own publications or supporting others through the publishing process. That sort of work isn’t, by and large, what we trained for, and perhaps more importantly, it isn’t the kind of thing for which we get credit.4

Even more, there is the question of prestige: scholars continue to publish in venues that have established imprimaturs, and in venues that they have no editorial hand in, because those two factors continue to be privileged by the various review mechanisms up the chain. Scholars need to persuade internal and external review committees that their work has been selected through an impartial, rigorous review process, and all the better if the name of the organization that runs that review process resonates. But of course publishing collectives are capable of being just as (if not more) rigorous, and scholarly associations like my own can provide not just an imprimatur for those collectives but also access to the many other members in the field that the collectives would likely want to reach.

http://blogs.lse.ac.uk/impactofsocialsciences/2015/10/21/opening-up-open-access-kathleen-fitzpatrick/

Opening Up Open Access: Moving beyond business models and towards cooperative, scholar-organized, open networks.


** notes
*** liu
# 2018-05-14

the answer to this question, i suggest, is critique at the level of, and articulated through, infrastructure–where “infrastructure,” the social-cum-technological milieu that at once enables the fulfillment of human experience and enforces constraints on that experience, today has much of the same scale, complexity, and general cultural impact as the idea of “culture” itself.  indeed, it may be that in late modernity when the bulk of life and work occurs in organizational institutions of one kind or another, the experience of infrastructure at institutional scales (undergirded by national or regional infrastructures such as electricity grids and global-scale infrastructures such as the internet)

# 2018-05-14

, critique seeks to turn its complicity to advantage–for example, by positioning critics as what foucault called embedded or “specific intellectuals” acting on a particular institutional scene to steer social forces.  a related idea is to go “tactical” in the manner theorized by michel de certeau, who argued that people immured in any system can appropriate that system’s infrastructure through bottom-up agency for deviant purposes (as in his paradigm of jaywalking in the city).  media critics, including new media critics, have generalized de certeau’s notion in the name of “tactical media,” meaning media whose platforms, channels, interfaces, and representations can be appropriated by users for alternative ends.

# 2018-05-14

pdf) and ackbar abbas and david theo goldberg’s “poor theory” (which uses “tools at hand” and “limited resources” to engage “with heterogeneous probings, fragmentary thinking, and open-endedness” in resistance to “totalization, restriction, and closure”) (



sheila anderson observes


sheila anderson points out that there was an inflential repoprt on "cyberinfrastrcture" that set the tone of much funding in recent memory (atkins report) and the john unsworth report for the social sciences and humanities (8)


what's the deal with the digital humanities getting money because funding agencies what to fund things that are new and exciting, and that fit their political/economic goals?



despite the references to people and organisations, there remains within all the three examples an idea of infrastructure as a thing with a subtle and underlying discourse of the material nature of infrastructures; infrastructure is built, it is the tools, the digital libraries, the data, it is a software component or an application – it is, as leo marx argues, ‘the material component’ of the infrastructure folded into an ‘aura of phantom objectivity’. 17 this idea of materiality, of existing as a thing to be built, is compounded by the idea of being primarily about technology or systems. despite the well-made arguments put forward to define systems as inclusive of social, political and economic factors, nevertheless the talk remains about moving from systems to networks to internetworks with the primary focus on the technology. the debate is more about a question of control, centralisation versus federation, heterogeneity versus homogeneity, from bounded systems to an internetwork, all of which emphasises the material technological components of the infrastructure. even the more nuanced approach put forward in unsworth’s acls report still frames infrastructure as something that is to be ‘built’, something to be ‘developed’, that can be specified, designed and constructed in much the same way as we might design a building. infrastructures in this context are also expensive, hard to change, and with an air of irreversibility about them (sheila anderson 9)

# what would reversible/flexible infrastructure look like? forkable curriculum? is a wiki flexible or an example of path dependence?




"however, during a conference in cologne in 2012, it became clear that not everyone shares a positive view of these developments. the cologne conference, the first in a series 5sheila anderson organised by manfred thaller, was called ‘the cologne dialogues on the digital humanities’. thaller gathered together a group of scholars to debate a pre-defined set of controversies in the digital humanities. the first, and workshop defining, controversy debated the question ‘do the digital humanities have an intellectual agenda or do they constitute an infrastructure?’. this is a loaded question, the implication being that if the digital humanities constitute an infrastructure then it cannot have an intellectual agenda.

in answering the question willard mccarty, a leading advocate and scholar in the digital humanities, argued that the discipline has suffered through its association with infrastructure development because to participate in such development is to relegate the discipline to a state of servitude. this, mccarty continued, is not to suggest that there is anything intrinsically wrong with infrastructure development, but rather to suggest that to focus on infrastructure requires the digital humanities to act in support of the research agenda of others rather than defining and carrying out its own research agenda. digital humanists are defined as servants and not as scholars. 8 it is not uncommon to view infrastructure as a substrate or the ‘subordinate parts of an undertaking’ as defined by the oxford english dictionary. a somewhat modified definition is provided by the american heritage dictionary which at least assigns some sense of value to infrastructure defining it as ‘the basic facilities, services and installations needed for the functioning of a community or society’. but the key defining factor remains that infrastructure acts in a support role to something that is more important. (sheila anderson 5-6)

# infrastructureb envy


# path dependence
# majoritarianism



* Norbert Wiener
** Human Use Of Human Beings

... any pretence of harmlessness was out of the question for him. From the time of the end of the war until his death in 1964, Wiener applied his enetrating and innovative mind to identifying and elaborat­ ing on a relation of high technology to people which is benign or, in his words, to the human - rather than the inhuman - use of human beings. In doing so during the years when the cold war was raging in the United States, he found an audience among the generally educated public. However, most of his scientific colleagues - offended or embarrassed by Wiener's views and especially by his open refusal to engage in any more work related to the military - saw him as an eccentric at best and certainly not to be taken seriously except in his undeniably brilliant, strictly mathematical, researches. Albert Einstein, who regarded Wiener's attitude towards the military as exemplary, was in those days similarly made light of as unschooled in political matters. Undaunted, Wiener proceeded to construct a practical and comprehensive attitude towards technology rooted in his basic philosophical outlook, and presented it in lucid language. For him technologies were viewed not so much as applied science, but rather as applied social and moral philosophy. Others have been critical of technological developments and seen the industrial revolution as a mixed blessing. Unlike most of these critics, Wiener was simul­ taneously an irrepressibly original non -stop thinker in mathematics, the sciences and high technology and equally an imaginative critic from a social, historical and ethical perspective of the uses of his own and his colleagues' handiwork. Because he gave rather unchecked rein to both of these inclinations, Wiener's writings generate a particular tension and have a special fascination. Now, four decades later, we see that the tenor of his comments on science, technology and society were on the whole prophetic and ahead of his time. In the intervening years his subject matter, arising out of the tension between technical fascination and social conscience, has become a respectable topic for research and scholarship. Even leading universities have caught up with it and created courses of study and academic departments with names such as 'science studies', 'technology studies' or 'science, technology  (xi-xii)

* hacking
from here: https://www.wired.com/2014/11/what-is-a-hacker/

definition from Facebook is more about expedience

Andrew Bosworth

DIRECTOR OF ENGINEERING, FACEBOOK
At its core, hacking is an approach to problem solving. It is both humble and optimistic in its conviction that anything that has been built, including by the hacker herself, can be improved. It is skeptical of complex solutions. It believes in people and thus assumes that if lots of people are working in one direction without success then the answer must lie in another direction. It believes that a good solution today is better than a great solution tomorrow. It does not believe that done is better than perfect so much as it believes that being done sooner is the best path to eventual perfection, though it is also skeptical that perfection exists. It believes in failing fast and sharing both successes and failures openly so that others can build on what has been done. Having conquered one problem, it doesn’t linger but rather moves quickly to the next challenge.

Let us consider a concrete example. When we are getting close to launching products at Facebook we often move the product team out of our usual open floor plan and into a room so they can coordinate in even tighter loops. As a rapidly growing company, it can sometimes be hard to find the space for these so-called war rooms. Before the launch of our games platform we needed to move more people into a war room than could possibly fit in any floor plan. Not to be defeated, the team came in over the weekend and built a loft which could support desks on two levels. This is classic hacking. The team solved a problem on a dimension, quite literally, that was unexpected: when you think of a floor plan you think of width and depth, not height.

Not to be outdone, a few years later when the Messenger team needed to move 15 people into a war room but the largest room we had could only fit 10 people any way you arranged it (including vertically), they cut a hole in the wall and made a bigger room. This example isn’t illustrative for its cleverness but rather for its power as a metaphor. As humans when we walk into a room we are inclined to perceive the four walls around us as permanent, immovable constraints. Some of them are — we should avoid demolishing structural walls — but most of them probably are not. The hacker, by being skeptical of even the most basic accepted truths, sees through walls in a way that others do not.

(Reprinted from Boz blog.)

Cover photo: Canonical MIT hacker Bill Gosper, by Michael Beeler.


# curb cuts and people going out at night to hack them
https://99percentinvisible.org/episode/curb-cuts/
* Hale Zukas Papers, 1971-1998
** Outreach to the Disabled and Blind
https://oac.cdlib.org/ark:/13030/hb4m3nb0b4/?brand=oac4

For a large number of the newly disabled and blind and those who still languish within the confines of their home or an institution (nursing homes, hospitals, etc.), outreach is largely non-existent. Most rehabilitation agencies only accept referrals and put little emphasis on actually making initial contacts. While those blind and disabled who are aged or belong to an ethnic minority suffer higher disability rates, they are among those who suffer most from exclusion.

The Center for Independent Living will contact these blind and disabled both individually and collectively through counseling field work (to be largely carried out by blind or disabled staff counselors), public service announcements, coverage in the media, and by linking ourselves to community switchboards. The purpose of this outreach is to increase awareness of the wide range of life experiences and accomplishments that are open to them, as well as the services provided by the Center for Independent Living and the other service agencies for which they are eligible. This service will be buttressed by such programs as inviting clients to the homes of independent blind and disabled and informal meetings of the C.I.L.

Home|Browse Institutions|Browse Collections|Browse Map|About OAC|Help|Contact Us|Terms of Use
The Online Archive of California is an initiative of the California Digital Library.
Copyright © 2009 The Regents of The University of California
** 


* Judy Heumann
https://vimeo.com/102393586
There was a lot of...there was work being done in research in public policy activities in the world of disability but basically it wasn't being strongly influenced by the voices of disabled people. So one of the prime purposes of the creation of the World Institute on Disability was to bring the voices and vision of disabled individuals into the public policy arena in the area of disability.

* unhuman
Why is the mind in the head? Because there, and only there, are hosts of possible connections to be formed as time and circumstance demand. Each new connection serves to set the stage for others yet to come and better fitted to adapt us to the world, for through the cortex pass the greatest inverse feedbacks whose function is the purposive life of the human intellect. The joy of creating ideals, new and eternal, in and of a world, old and temporal, robots have it not.
McCulloch


# on the role of libraries
# svenson
:quote:
http://digitalhumanities.org/dhq/vol/4/1/000080/000080.html

Libraries are an important part of the infrastructure of the humanities, and in a sense, a kind of humanities laboratory [7] placed outside the departments and schools. Libraries are also, by default, important players in relation to humanities-based information and information technology. It is important to acknowledge, however, that traditional research libraries come with a set of epistemic commitments pertaining to the role of collections, the types of texts handled, tool building, collaboration with humanities scholars and distribution (see [Drucker 2009b] for a critical discussion).
:end:

* Woman on the Edge of Time

Rocket ships, skyscrapers into the stratosphere, an underground mole world miles deep, glass domes over everything? She was reluctant to see this world. Voices far, near, laughter, birds, a lot of birds, somewhere a dog barked. Was that—yes, a rooster crowing at midday. That pried her eyes open. A rooster? Fearfully she stared into Luciente’s face, broken open in a grin of triumph. “Where are we?”







* Builders and Sustainers of the Independent Living Movement in Berkeley : Volume IV
# http://content~u.cdlib.org/view?docId=kt2779n58v&&doc.view=entire_text
Pachovas
It was amazing how simple pleasures, like a can of tuna, can really brighten up an otherwise dreary life. Now, Jerry Brown had gotten into the act and got the legislature to support his taking a bill, by hand, to Washington to lobby the president to try to pass the National Wild and Scenic Rivers Act. So he went off to Washington. Every day as we were getting colder, we were getting word that what we were doing was very successful and that we should stay put. So they were doing all this lobbying in the background.

On the tenth day that we were up there, and it was cold--and then the worst thing that happened physically is that Kale punched a knife through a pie pan and stuck it into the air mattress that I was sitting in--depriving me of any way of not hurting when I sat on the ground. So we were trying to do lots of little funny patches, trying to keep the air in, but mostly having to repump this thing up many times a day. And I started developing a bit of a kidney infection because we just weren't drinking enough.


Breslin
Yes.


Pachovas
We couldn't have warm water and the cold water was just unpalatable on a really cold day, but nonetheless, we held out. It was sort of intrepid.

― 287 ―
Dan Ellsberg decided that he was going to do this big vigil in San Francisco for us and bring more light to bear on this whole situation. The one thing that we didn't anticipate because none of us was so-minded, was that it was the opening of duck season. We hadn't thought of that. [laughter] So it was legal for anybody who was mad about what we were doing to go riding around with a shotgun looking for us, which they did.


Breslin
Sitting ducks, as it were.


Pachovas
We were. It was amazing, because at one point, about on the ninth day, I remember waking up and hearing--and we got used to talking really quietly because your voice would just boom across the canyon. We'd hear this, "Quack, quack, quack--quack, quack, quack--quack, quack, quack." Now, the previous day people had ridden by in boats, calling us out by name, just wondering if we would respond. We just stayed hidden. Everybody was looking for us: the sheriff and the police. And, well, the idiots were looking on the wrong side of the dam. They were looking up river, on the river part of it, and we were down below where the dam was, so it was kind of this exercise in stupidity. But every once in a while surveillance planes and things would fly by and we'd cover everything up with the earth covered stuff and try to make ourselves as inconspicuous as possible and be still so no one could find us. There was this massive search to try to find us. As I said, the previous day, people had been trying to call us out, saying it was okay to come out, and when we peeked out we saw there were men in boats with guns, so we didn't want to do that.



#+BEGIN_QUOTE
I learned back then that it was not some benevolent church group that carved out those curb cuts, or a member of the town council trying to get votes who mandated accessible facilities, they were due to the deliberate actions and painstaking labor of members of the disability community who fought for the changes that were made. Their work set the stage for the ongoing struggle for rights and liberties that has engaged a nation of activists. Today, while discrimination remains a constant in disabled people's lives, the right to an accessible environment, to housing, employment, and transportation is governed by laws that are increasingly exerting influence on those who discriminate. Further, the idea of integration, in education, in public accommodations and in transportation, pervades the informed discourse on disability rights and is supported, again, by legislation that mandates desegregating society.
#+END_QUOTE


#+BEGIN_QUOTE
Political action kept pace with the developing awareness and institutional growth. In the early seventies, the Berkeley group successfully lobbied the city of Berkeley for curb cuts and the state legislature for attendant care funding. In 1977, scores of persons with disabilities sat in for twenty-six days at the offices of the federal Department of Health, Education, and Welfare in San Francisco, as part of a nationwide protest that eventually forced implementation of Section 504 of the Rehabilitation Act of 1973, often called the Bill of Rights for Americans with Disabilities. Many participants trace their awareness of disability as a civil rights issue and their sense of membership in a disability community to the 1977 sit-in.
#+END_QUOTE

#+BEGIN_QUOTE
It seems to always get kind of left out of the history, [laughter] so I'm going to just throw it in there because it was, I think, a very important part. People don't realize a lot of these great ideas came after two or three joints. [laughter] You know? I mean, I'll tell you, I can remember living up at Cowell Hospital and tooling all the way down, which then was a long ways, in a twelve-volt wheelchair, from the top of Cowell Hospital all the way down to Ward Street, which is where Ed Roberts lived, on Ward Street, and getting very, very stoned, drinking good wine, smoking very good marijuana, and thinking of great ideas about how we could change this, where we could put a curb cut, or what we could do next. That's kind of always left out.

Johnson
So let's talk some more about the wild things. Is it personally that might have been part of the way you were trying to make your existence normal as opposed to the way of being viewed by the rest of society?


Chavez
Well, I think it was, and I think it was also a way for the disabled people to get together and socialize. You know, because Cowell Hospital itself was very isolated. I mean, we were at the top of the mountain, literally. We were across from the football stadium, which is way up there. We couldn't just sort of casually say, "Well, let's go out for a beer." You know, I mean, if you were going to do something like go to Telegraph Avenue, that was an adventure. Yes, I mean, anything where you left the hospital was an adventure.

Being also isolated at the hospital, you were kind of stuck there for a lot of hours; and kind of stuck in that kind of situation with ten, twelve other people, it's pretty natural that you're going to end up, you know, drinking or partying or whatever. I mean, you're not going to study all the time, and we didn't. I think partying was a big part of the socializing that went on. We would also have these big dinners, I remember, where we'd have this outside cook come in and cook for the students, and that was a real social part of it.

There were some of the early experiences of poker games at the first CIL which was on Haste Street. I happened to be dating a woman that lived in the same building and so I would often go over and frequent these poker games, or we would have poker games at her house or parties or whatever.

But partying was a very big part of that whole time; it wasn't just us as disabled students. I mean the early and mid-seventies period was just a very open kind of period--not just drugs and partying, but very open sexually, too--and so disabled people were really exploring those boundaries as well. I mean, a lot of relationships and things were going on in that way, and that was very eye-opening for me. I was always very much into the opposite sex, and there was a lot of dating between attendants and people they worked for, and vice versa with attendants and attendants and disabled people and disabled people, and it was a very active time.

#+END_QUOTE

#+BEGIN_QUOTE
I mean, this coliseum example, all this renovation is a great example because we're probably going to end up winning this lawsuit and then they're going to have to go back and spend all these millions more to change what if they had done it right the first time, if they had just followed the law, wouldn't have been that much of an issue and would have saved them a lot of money in the long run and made it better for everybody. Because that's the irony: everybody I've ever talked to that has dealt with specifically architectural barrier type situations find that it's better for the overall populace.

I mean, all you have to do is look at curb cuts and see, okay, well, who utilizes curb cuts? People on bicycles, people on skateboards, mothers with babies in baby carriages, little old ladies and their shopping carts. I mean, everybody utilizes curb cuts. It's just something that makes sense. Most of the things
#+END_QUOTE



** curb cut story
http://content.cdlib.org/view?docId=kt4c6003rh;NAAN=13030&doc.view=frames&chunk.id=d0e1280&toc.id=d0e1280
-- 23 --
[Eric] Dibner

..

And the same is true today. If you can't get in the front door, it doesn't work. When I looked for this house, for instance, when Om Devi and I moved here a couple of years ago,

― 24 ―
we had to find a place that was close enough to the ground it could be ramped.
Hessler lived on a place on Haste Street right around the corner from where I work now which was a cottage behind a large older apartment building. It had one step at the door and one step at the porch and so I built a little wooden ramp for him to get up to the porch and then to get up into the apartment. I guess maybe we had done that in France, I'm trying to remember. I think maybe we had to build a little ramp in France, so that was one of my first experiences with ramps, right, and learning that if you're closer to the ground, you don't have to build so much of a ramp, like, duh! [laughs]


Cowan
I certainly have heard your name associated with ramps over and over again, Eric. There is this story that you were building curb cuts and ramps in Berkeley sort of unofficially. Is there a story behind that?


Dibner
Well, you didn't hear about the nitroglycerin where we were blowing up curbs and [laughter] and jackhammers in the middle of the night, where we'd go and we'd jackhammer up all these intersections and then the city would have to fix them.


Cowan
No, I didn't hear that story. Is that a true story? [laughs]


Dibner
No, neither of those are true stories, actually. [laughs] That was a little later when Ed asked for some ramps to be--there were some corners where he had problems going from his house to CIL, or maybe it was the Disabled Students' Program. So I got a bag of cement and went out. They were real low curbs, like a couple of inches, at Dana and Dwight, probably at Ellsworth and Dwight, and I think I did one at Ellsworth and Blake. It was just to bevel the corner. I mean, we didn't build curb ramps, we just put some cement down to make it useable.


O. Dibner
They were the first ramps.


Dibner
There were curb ramps in other places at that time.


O. Dibner
Oh, were there?


Dibner
Yes.


Cowan
I did read that the city rebuilt--this was in Hale's [Zukas] interview--that the city rebuilt Telegraph Avenue and did ramps.


** accidental access
http://content.cdlib.org/view?docId=kt4c6003rh;NAAN=13030&doc.view=frames&chunk.id=d0e1280&toc.id=d0e1280

-- 25 --
This was a design that happened earlier in the century and it wasn't for access as much as it was for pedestrians to not have to step down at the corner. The water goes underneath the corner in a cross culvert, and that allows the intersection to stay kind of flat. I think that feature also was something of a catalyst in making it possible to live in this area.

In the seventies, also, there were a lot of ticky-tacky apartment buildings built with elevators. And even though the elevators might be kind of tiny and there's other problems with the buildings, they're flat. Some of them have steps and some of them don't have steps, but generally you roll in and you can get in to the elevator. It was a massive availability of housing. The bathrooms might not be accessible but at that time people I worked with were using commodes, just not going into the bathroom.


** hacker shit
Cowan
Do you recall, in terms of living independently, any kinds of gadgets or things people put together to make it easier?


Dibner
Yes, these were memorialized in a booklet that Susan [O'Hara] provoked be put together which showed a bunch of assistive technology--primitive assistive technology, or what we would call low-tech, these days--in use. Mary Ann Hisermam and John Hessler are in that booklet. There's a product called pip which is a rubber lever handle on a door, so that's one kind of thing. Another is one is a string on the doorknob so you can pull the door closed behind you without backing your wheelchair against it. Other things are extension handles on keys and extensions on the turn latch on a lock--you can just tape a stick on it.

Let's see--Scott had a long reacher stick. He had a dowel, Scott used a dowel to reach things. I think he also had one of those reachers that you squeeze and it grips. So some of these things were available in the medical industry already. But some of them were just adaptations that people made.

The concept in adaptive devices and the assistive technology really is reach and ramp to me. A ramp is a bevel between two elevations. You're trying to get from point A to point B. And reach is bringing the object closer to you by extending it or changing its shape somehow so it's more manipulable. These are principals that carry through in the accessibility standards today.

In order to reach something you need location--you might have to move it closer--and ease of operation--it has to turn easily. So you extend it to make it a lever, which gives you greater force and also brings it down closer to you.

To me, the ramp is really symbolic, in a way, of how I see proceeding through the system. You're trying to get from point A to point B and you need to figure out how to lever your way--a ramp is a lever--and you need to figure out how to move objects that are blocking your path. So I use that analogy a lot in looking at how we're trying to do things. People aren't really trying to make a different world; they're just trying to build ramps.




# hardcore disabled
# old article
https://www.washingtonpost.com/archive/opinions/1981/06/07/stop-caring-for-the-disabled/2ea92fe5-8b02-4e32-a5a2-077b87da782d/?noredirect=on&utm_term=.b7663808db19

* sort

BUMMER platform
https://lareviewofbooks.org/article/delete-your-account-a-conversation-with-jaron-lanier/#!


* nudge stuff
https://aeon.co/essays/our-behaviour-in-bulk-is-more-predictable-than-we-like-to-imagine
