#+OPTIONS: toc:nil

* Brief Summary

/Negotiated Access/ is an argument that technology should serve people, rather than people serve technology. It focuses on points of negotiation, a term defined within the project to describe the place of interaction between an individual and a community, or a community and the larger society. At these points of negotiation, individuals and communities either exercise their own autonomy to serve their values, or, alternately, are exploited by those who control the immediate social or built environment. The project considers the problem of negotiation, first in the context of communities of people with disabilities and expanding outward to encompass the humanities within the academy, the academy within the public sphere, and eventually humanity within an ecology of its own creation—the unhuman. The project is situated within disability studies, but also draws on memoir, utopian studies, the digital humanities, and the public humanities.

* Description of Included Chapter

The included chapter, Chapter 1, introduces the concept of negotiation and draws comparisons between the shared concerns of people with disabilities and hacker subculture, leading up to an introduction of the concept of haccessibility. It follows an introduction that suggests that new, more person-centered forms of technology are required to counter an array of trends that dispossess individuals and local communities. Though I have written another chapter, Chapter 3, this chapter excerpt has been chosen as more representative of the project as a whole.

* Progress to Date

To date, I have completed drafts of Chapter 1 and Chapter 3 and have begun to draft an introduction. I have written approximately 19,000 words, and would conservatively estimate the project to be around 35% complete.

* Significance to Disability Studies

Within the disability rights movement and disability studies, two competing and largely incompatible models of disability have come to dominate conversations about disabled individuals and their place in a wider, largely able society. The medical model, which seeks to normalize or remedy pathology and efface difference, emphasizes the disabled body as the source of friction between disabled people and society. The medical model argues, implicitly, that ranges of human capability and experience that fall outside normative bounds must be corrected, and so the proposed way forward for people with disabilities is the cure. In recent years, a second model of disability, the social model, has been advanced by disability scholars and advocates. The social model views disability as socially constructed, the result of society's unwillingness to provide reasonable accommodations and the fear, stigma, and low expectations directed at disabled individuals by the able. This model focuses primarily on society as a whole, and articulates a way forward based on advocacy, awareness, and political change.

The social model has repeatedly demonstrated its usefulness, primarily as a tool for productive change in society—manifest in localized reforms such as the Americans with Disabilities Act—but to a lesser extent as a productive lens for theorizing disability in the academy. Recent discussions about the social model among scholars such as Liz Crow and Tom Shakespeare have suggested that the social model, while critical for activism, should be expanded to include a more diverse and holistic conception of disabled experiences. While the social model is, and continues to be, a powerful and effective impetus for change, its focus on the wider society places only secondary emphasis on the day-to-day concerns and considerations of people with disabilities—that is, the myriad adaptations, workarounds, resiliences, individualized skills, and acts of provocation and resistance that allow people with disabilities to survive and(sometimes) thrive in an able world. My thesis project, /Negotiated Access/, seeks to closely examine this locus of interaction between the disabled individual and their lived environment. Rather than center analysis on the disabled body (the medical model) or the society at large (the social model), /Negotiated Access/ proposes to interrogate points of interaction—negotiation—among disabled people and their physical and social environment, with attention to adaptations that allow people with disabilities to distinguish themselves, rather than efface or obscure differences. The project seeks to contribute to ongoing conversations in disability studies by answering one question: what knowledges, community, or infrastructure provide for a way forward for people with disabilities independent of the approbation or approval of able society?

Core to this project is the concept of /negotiation/, a term advanced here to describe forms of interaction among disabled people, society, and the lived environment. Drawing on their understanding of their own situation and their relationship with the spaces, people, and objects around them, the disabled individual /negotiates/. That is, they negotiate their environment, navigating spaces and reforging relationships among their own bodies and the physical world. They negotiate with others, learning to survive in social milieus often characterized by ignorance and hostility. They share, build, and teach amongst themselves, creating negotiables—knowledge, physical infrastructure, and social capital that are their own. Negotiation in this sense, therefore, is about movement, interaction, creation, understanding, and the formation of community, all in service of an individual's own values, rather than the values imposed on them by a society unresponsive to their needs.

Though this project is grounded in disability studies, my third and fourth chapters apply concepts articulated in that context, including negotiation and haccessibility, in wider contexts.



* Chapter Descriptions

/Negotiated Access/ is planned as four chapters. The first, as described above, introduces the concepts of negotiation and haccessibility. The second explores these concepts through readings of disability memoir and also touches on my own experiences with disability and creating infrastructure for my own needs and the needs of communities I participate in. The third and fourth chapters seek to apply the concept of negotiated access in other interdisciplinary fields beyond disability studies. The third chapter examines practices of negotiation in the field of digital humanities, showing how scholars in DH and related fields have been able to create infrastructure and methodologies that reflect their own values, providing alternatives to a prevailing commercial or corpratist ethos in the development of "technology"—itself a disputed term in this context. The fourth and final chapter applies negotiated access to the field of utopian studies, analyzing science fiction literature that engages with uncommon or estranged interactions among individuals and their lived environments, expanding negotiation out to encompass humanity and the idea of the "unhuman" advanced in the introduction.

My first chapter attempts to answer two primary questions. First, how have people with disabilities provided for themselves in ways not dependent on changes to the wider, largely able society? Second, why does it matter that people build community and infrastructure for themselves, rather than allow these things to be built for them? This first chapter opens with a case study, describing a blind individual, Terry Garrett, who garnered attention that extended to the able community after completing a game thought to be accessible only to the sighted. Garrett's achievement provides an entry point to discussion of a relatively unknown community of hackers and tinkerers with mobility, sensory, cognitive, and other disabilities who have built relationships and infrastructure around shared causes and concerns. In seeking to understand the importance of these communities, the chapter draws parallels to "hackers"—both the enthusiasts who shaped the culture and conventions of early computing and those skilled in circumventing security to gain unauthorized access to systems.

My second chapter will frame the issues at stake with understanding the history of negotiation through careful analysis of a set of memoirs such as Brown's /My Left Foot/, Keller's /The Story of my Life/, and the Barron family's /There’s a Boy in Here/, accounts that can be understood as troubled or incomplete—"auto-ish biographies." This analysis will be augmented by brief discussions of devices and prosthetics such as the "talking glove" described in the 1680 /Didascalocophus: or the deaf and dumb mans tutor.../ and the 1930s "talking books" for gramophone, devices which fit a dominant narrative of able intercession but, when interrogated, also attest to the isolation and marginalization of people with disabilities.

My third chapter, focused on infrastructure creation in the digital humanities, shows how the concept of negotiation can apply to other communities whose values are not represented by the society more broadly. The modern humanities advocates for a set of values that are, generally speaking, not reflected, at least fully, by the culture at large. These range from a stance against neoliberalism and other commercial and corporatist ideologies to the acknowledgment and defense of marginalized communities to an emphasis on openness, preservation, and the free exchange of knowledge. These values, however, are not always reflected in the ways those in the academy go about their work. However, in recent years, critical infrastructure studies, platform studies, and groups within the digital humanities and library science are bringing infrastructure into the foreground, imagining what it would mean for the humanities to be considered a public resource and analyzing the unstated assumptions underlying the commercial infrastructure that has stolen, largely unacknowledged, into the humanities.

My final chapter, focused on utopian literature, will consider literary explorations and reimaginings of negotiation, or the locus of interaction between the individual and the lived environment. This chapter will use texts that present the body's boundaries as shifting and liminal to question ascendant narratives, associated with transhumanism and technosolutionism, that present universal human traits, or humanity in general, as pathological. These views, which position technology as a force that will "uplift" humanity to a more perfect, efficient/productive, or transcendent state, are most explicitly articulated by futurists such as Ray Kurzweil (/The Singularity Is Near/, /The Age of Spiritual Machines/), but are endorsed tacitly or implicitly by the technology industry more broadly. In this chapter, I will use both speculative fiction and speculative nonfiction in service of a theory of negotiation that argues against an ideal of perfection that regards humanity as inherently inferior and in need of improvement through technological uplift.
