#+OPTIONS: toc:nil

People with disabilities have always needed to contend with physical and social structures designed for others, but not for them. Two competing and largely incompatible models of disability have come to dominate conversations about disabled individuals and their marginalized place in the wider, largely able society. The medical model, which seeks to normalize or remedy pathology and efface difference, emphasizes the disabled body as the source of friction between disabled people and society. The medical model argues, implicitly, that ranges of human capability and experience that fall outside normative bounds must be corrected, and so the proposed way forward for people with disabilities is the cure. In recent years, a second model of disability, the social model, has been advanced by disability scholars and advocates. The social model views disability as socially constructed, the result of society's unwillingness to provide reasonable accommodations and the fear, stigma, and low expectations directed at disabled individuals by the able. This model focuses primarily on society as a whole, and articulates a way forward based on advocacy, awareness, and political change.

The social model has repeatedly demonstrated its usefulness, both as a tool for productive change in society—manifest in localized reforms such as the Americans with Disabilities Act—and as a productive lens for theorizing disability in the academy. While the social model is, and continues to be, a powerful and effective impetus for change, its focus on the wider society places only secondary emphasis on the day-to-day concerns and considerations of people with disabilities—that is, the myriad adaptations, workarounds, resiliences, individualized skills, and acts of provocation and resistance that allow people with disabilities to survive and(sometimes) thrive in an able world. My thesis project, /Negotiated Access/, seeks to closely examine this locus of interaction between the disabled individual and their lived environment. Rather than center analysis on the disabled body (the medical model) or the society at large (the social model), /Negotiated Access/ proposes to interrogate points of interaction—negotiation—among disabled people and their physical and social environment, with attention to adaptations that allow people with disabilities to distinguish themselves, rather than efface or obscure differences. The project, broadly speaking, seeks to answer one question: what knowledges, community, or infrastructure provide for a way forward for people with disabilities independent of the approbation or approval of able society?

Core to this project is the concept of /negotiation/, a term advanced here to describe forms of interaction among disabled people, society, and the lived environment. Drawing on their understanding of their own situation and their relationship with the spaces, people, and objects around them, the disabled individual /negotiates/. That is, they negotiate their environment, navigating spaces and reforging relationships among their own bodies and the physical world. They negotiate with others, learning to survive in social milieus often characterized by ignorance and hostility. They share, build, and teach amongst themselves, creating negotiables—knowledge, physical infrastructure, and social capital that are their own. Negotiation in this sense, therefore, is about movement, interaction, creation, understanding, and the formation of community, all in service of an individual's own values, rather than the values imposed on them by a society unresponsive to their needs.

/Negotiated Access/ is planned as four chapters. The first, focused primarily on the field of disability studies and the wider community of people with disabilities, introduces concepts and case studies that shine a spotlight on work that is already ongoing in communities created by people with disabilities. This section advances the concept of "haccessibility," or the ability of people with disabilities to forge a path toward access that does not require the approval or assistance of the wider able community. The second chapter serves as a history of negotiated access as it has been, and continues to be, practiced in the disability community, and aims to uncover an obscured history of people with disabilities creating their own knowledges, community, infrastructure, and other "negotiables," allowing them to survive in an able society. The third and fourth chapters seek to apply the concept of negotiated access in other interdisciplinary fields beyond disability studies. The third chapter examines practices of negotiation in the field of digital humanities, showing how scholars in DH and related fields have been able to create infrastructure and methodologies that reflect their own values, providing alternatives to a prevailing commercial or corpratist ethos in the development of "technology"—itself a disputed term in this context. The fourth and final chapter applies negotiated access to the field of utopian studies, analyzing science fiction literature that engages with uncommon or estranged interactions among individuals and their lived environments.

My first chapter attempts to answer two primary questions. First, how have people with disabilities provided for themselves in ways not dependent on changes to the wider, largely able society? Second, why does it matter that people build community and infrastructure for themselves, rather than allow these things to be built for them? This first chapter opens with a case study, describing a blind individual, Terry Garrett, who garnered attention that extended to the able community after completing a game thought to be accessible only to the sighted. Garrett's achievement provides an entry point to discussion of a relatively unknown community of hackers and tinkerers with mobility, sensory, cognitive, and other disabilities who have built relationships and infrastructure around shared causes and concerns. In seeking to understand the importance of these communities, the chapter draws parallels to "hackers"—both the enthusiasts who shaped the culture and conventions of early computing and those skilled in circumventing security to gain unauthorized access to systems. Like hackers, people with disabilities are often attempting to seek access to a location or system from which they have been excluded. Both hackers and disability affinity groups frequently seek to retrofit or repurpose existing resources to fit their own goals, and both groups gravitate toward an ethos of freely sharing knowledge and capabilities.

Tracing these connections between communities that self-describe as "hackers" and disabled communities of practice allows the introduction of a concept—"haccessibility"—that describes an important but rarely-discussed aspect of the relationship between the disabled individual and society. Through established "ways forward"—modes of integrating people with disabilities and able society—people with disabilities can frequently, even consistently, exceed the (often low) expectations with which they are faced. However, they are still all-too-often placed in a difficult or impossible position by society's inability or unwillingness to adapt to their needs. In such cases, the disabled individual has a last way forward: haccessibility, or forging a path to access by one's own resources or through the resources of one's community. This section will advocate for haccessibility as a means of understanding the multivalent intersections among individuals and their social and technological contexts. It will also provide examples of ways in which institutional morays, practices, and rules have been (and often must be) violated by disabled individuals in pursuit of their goals. This chapter will draw on works such as Donna Haraway's /Cyborg Manifesto/, Richard Stallman's /Free Software, Free Society/, and Scott Dexter and Samir Chopra's /Decoding Liberation/ in addition to foundational works in disability studies, especially those relating to and critiquing post- and transhumanism. The chapter will also examine communities that have formed around the practice of hacking personal infrastructure, such as [[http://blarbl.blogspot.com/][Blind Arduino]], [[https://www.nvaccess.org/][Nonvisual Desktop Access (NVDA)]], [[https://www.reddit.com/r/disabledgamers/][Disabled Gamers]], and [[http://hearinghacks.com/][Hearing Hacks]].

My second chapter will frame the issues at stake with understanding the history of negotiation through careful analysis of a set of memoirs that include Keller's /The Story of my Life/ and the Barron family's /There’s a Boy in Here/, accounts that can be understood as troubled or incomplete—"auto-ish biographies." This analysis will be augmented by brief discussions of devices and prosthetics such as the "talking glove" described in the 1680 /Didascalocophus: or the deaf and dumb mans tutor.../ and the 1930s "talking books" for gramophone, devices which fit a dominant narrative of able intercession but, when interrogated, also attest to the isolation and marginalization of people with disabilities.

My third chapter, focused on infrastructure creation in the digital humanities, shows how the concept of negotiation can apply to other communities whose values are not represented by the society more broadly. The modern humanities advocates for a set of values that are, generally speaking, not reflected, at least fully, by the culture at large. These range from a stance against neoliberalism and other commercial and corporatist ideologies to the acknowledgment and defense of marginalized communities to an emphasis on openness, preservation, and the free exchange of knowledge. These values, however, are not always reflected in the ways those in the academy go about their work. However, in recent years, critical infrastructure studies, platform studies, and groups within the digital humanities and library science are bringing infrastructure into the foreground, imagining what it would mean for the humanities to be considered a public resource and analyzing the unstated assumptions underlying the commercial infrastructure that has stolen, largely unacknowledged, into the humanities. This chapter will argue that, just as it is important for disability affinity groups to create their own knowledge, community, and infrastructure that reflect their own concerns and values, the humanities also benefit from attending to negotiation, or the points of interaction between themselves and society. This chapter will draw on some of my own experiences developing infrastructure for teaching, advocacy, and accessibility in the academy, including work on [[http://dhbox.org/][DH Box]], a cloud-based laboratory for teaching digital humanities techniques; the [[https://digitalfellows.commons.gc.cuny.edu/2017/04/10/exploring-the-local-impact-of-the-neh-neh-impact-index/][NEH Impact Index]], an advocacy tool for showing the local impact of the National Endowment for the Humanities; and [[https://github.com/smythp/eloud][Eloud]], a screen reader for blind and low-vision coding and writing.

My final chapter, focused on utopian literature, will consider literary explorations and reimaginings of negotiation, or the locus of interaction between the individual and the lived environment. This chapter will use texts that present the body's boundaries as shifting and liminal to question ascendant narratives, associated with transhumanism and technosolutionism, that present universal human traits, or humanity in general, as pathological. These views, which position technology as a force that will "uplift" humanity to a more perfect, efficient/productive, or transcendent state, are most explicitly articulated by futurists such as Ray Kurzweil (/The Singularity Is Near/, /The Age of Spiritual Machines/), but are endorsed tacitly or implicitly by the technology industry more broadly. In this chapter, I will use both speculative fiction and speculative nonfiction in service of a theory of negotiation that argues against an ideal of perfection that regards humanity as inherently inferior and in need of improvement through technological uplift.

Fundamentally, /Negotiated Access/, as a project, is an argument that communities of practice should—and, perhaps, must—create their own knowledge and infrastructure.









, in the utopian novel 

* old



** utopian?

a number of 19th- and early 20th-century thinkers and writers engaged not only with the idea that technology could serve as a prosthetic for humanity, but that humanity could be a prosthetic for technology.


 in 1872, samuel butler, in the utopian novel /erewhon/, suggested not only the former—"[i]f it is wet we are furnished with an organ commonly called an umbrella, and which is designed for the purpose of protecting our clothes or our skins from the injurious effects of rain" (butler)—but also the latter: "[a]mong themselves the machines will war eternally, but they will still require man as the being through whose agency the struggle will be principally conducted" (butler). charles dickens, in novels such as /little dorrit/ and /dombey and son/, depicted technological forces such as the railway and social institutions such as the victorian prison system as self-aware entities that used, processed, and disposed of humanity while working toward their own obscure ends. at the same time, pseudoscientific (or "heterodox") disciplines such as vitalism and spiritualism advanced theories based on forces that pervaded both humanity and the material world. these include the theory of the odic force, a form of life energy that pervaded all things and that was used to explain phenomena such as will o' wisps and haunted houses. these 19th-century developments, when taken together, represent reactions to increasingly alien social and technological forces and an awareness, if vague, of the new interdependence between the human and the nonhuman.






aims to contribute an understanding of how disability studies can be informed by the ability of people with disabilities to advocate for themselves, build their own infrastructure, and successfully negotiate a society that is not their own.


 the current dialogue in disability studies is dominated by two models, a medical model that sees disability as a pathology to be cured or remediated and a social model that considers disability as socially constructed and which regards the disability rights movement as the primary way forward for people with disabilities. the social model of disability has provided a basis for great strides forward in the field of disability studies, both by supporting the disability rights movement and by providing a theoretical foundation for excellent scholarship on disability. however, the social model tends to focus, perhaps by necessity, on top-down methods for advancing the cause of people with disabilities. this project instead focuses on bottom-up or grassroots advances in the cause of people with disabilities, focusing primarily on the points of intersection among people with disabilities and their immediate social, physical, and cultural environment. these points of intersection, the shifting boundary that describes where the individual interacts with the broader world, i call "negotiation." negotiated access, therefore, is an understanding of disability that focuses on the ability of people with disabilities to negotiate their environment, in all the various meanings of that word.




* bibliography
“by design: remapping the colonial archive,” social text 33.4 (december 2015): 142-147.


didascalocophus, or the deaf and dumb man’s tutor, by george dalgarno (1628-1687)


1980-1998 /smith-kettlewell technical file
* TODO you have one job story for utopian?
