/Negotiated Access/, my dissertation project, aims to contribute an understanding of how disability studies can be informed by the ability of people with disabilities to advocate for themselves, build their own infrastructure, and successfully negotiate a society that is not their own. The current dialogue in disability studies is dominated by two models, a medical model that sees disability as a pathology to be cured or remediated and a social model that considers disability as socially constructed and which regards the disability rights movement as the primary way forward for people with disabilities. The social model of disability has provided a basis for great strides forward in the field of disability studies, both by supporting the disability rights movement and by providing a theoretical foundation for excellent scholarship on disability. However, the social model tends to focus, perhaps by necessity, on top-down methods for advancing the cause of people with disabilities. This project instead focuses on bottom-up or grassroots advances in the cause of people with disabilities, focusing primarily on the points of intersection among people with disabilities and their immediate social, physical, and cultural environment. These points of intersection, the shifting boundary that describes where the individual interacts with the broader world, I call "negotiation." Negotiated access, therefore, is an understanding of disability that focuses on the ability of people with disabilities to negotiate their environment, in all the various meanings of that word.

/Negoiated Access/ is planned as four chapters. The first, focused primarily on the field of disability studies and the wider community of people with disabilities, introduces concepts and case studies that shine a spotlight on work that is already ongoing in the disability community and introduces concepts such as "haccessibility," or the ability of people with disabilities to forge a path toward access that does not require the approval or assistance of the wider able community. The second chapter serves as a history of negotiated access as it has been, and continues to be, practiced in the disability community, and aims to uncover an obscured history of people with disabilities creating their own knowledges, community, infrastructure, and other "negotiables," allowing them to survive and (sometimes) thrive in an able society. The third and fourth chapters seek to apply the concept of negotiated access in other interdisciplinary fields beyond disability studies. The third chapter examines practices of negotiation in the field of digital humanities, showing how scholars in DH and related fields have been able to create infrastructure and methodologies that reflect their own values, providing alternatives to a prevailing commercial or corpratist ethos in the development of "technology"—itself a fraught term. The fourth and final chapter applies negotiated access to the field of utopian studies, analyzing science fiction literature that engages with uncommon or estranged interactions among individuals and their lived environments.

My first chapter attempts to answer two primary questions. First, how have people with disabilities provided for themselves in ways not dependent on changes to the wider, largely able society? Second, why does it matter that people build community and infrastructure for themselves, rather than allow these things to be built for them? This first chapter opens with a case study, describing a blind individual, Terry Garrett, who garnered attention that extended to the able community after completing a game thought to be accessible only to the sighted. Garrett's achievement provides an entry point to discussion of a relatively unknown community of hackers and tinkerers with mobility, sensory, cognitive, and other disabilities who have built relationships and infrastructure around shared causes and concerns. In seeking to understand the importance of these communities, the chapter draws parallels to "hackers"—both the enthusiasts who shaped the culture and conventions of early computing and those skilled in circumventing security to gain unauthorized access to systems. Like hackers, people with disabilities are often attempting to seek access to a location or system from which they have been excluded. Both hackers and disability affinity groups frequently seek to retrofit or repurpose existing resources to fit their own goals, and both groups gravitate toward an ethos of freely sharing knowledge and capabilities.

Tracing these connections between communities that self-describe as "hackers" and disabled communities of practice allows the introduction of a concept—"haccessibility"—that describes an important but rarely-discussed aspect of the relationship between the disabled individual and society. Through established "ways forward"—modes of integrating people with disabilities and able society—people with disabilities can frequently, even consistently, exceed the (often low) expectations with which they are faced. However, they are still all-too-often placed in the difficult or impossible position by society's inability or unwillingness to adapt to their needs. In such cases, the disabled individual has a last way forward: haccessibility, or forging a path to access by one's own resources or through the resources of one's community.

If infrastructure comprises material and social circumstances, such as roads, housing, communications systems, organizations, laws, and resources, that determine what is practical and possible, then haccessibility is the creation of personal infrastructure that expands the boundaries of the possible in ways that are personal, small-scale, and resistant to larger forces. The term can apply to anyone, whether teenagers (mis)using mentions of promoted brands on Facebook to receive a signal boost from its algorithm or the business executive who uses his desktop computer as a footstool. However, the term is most significant for the disabled, since adaptations, workarounds, prosthetics, individualized skills, and acts of provocation and resistance are critical to their ability to survive and thrive in an able world. Beyond its tendency toward self-determination, another critical aspect of haccessibility is its indifference to propriety and the need or desire to "pass" in wider society. Like the old-school hackers from which the term is derived, those who practice haccessibility often violate boundaries in order to expand their capabilities, explore their environment, and play at the boundaries of the acceptable, the possible, and the expected.

In addition to describing negotiated access and haccessibility, concepts intended to illuminate existing practices and knowledges in the wider disabled community, this first chapter also discusses the question of disabled identity—that is, whether there is such a thing as a unified disabled identity or whether disabled identity is, or should be, confined to specific affinity groups based on shared concerns.




* old
This section will advocate for haccessibility as a means of understanding the multivalent intersections among individuals and their social and technological contexts. It will also provide examples of ways in which institutional morays, practices, and rules have been (and often must be) violated by disabled individuals in pursuit of their goals. This chapter will draw on works such as Donna Haraway's /Cyborg Manifesto/, Richard Stallman's /Free Software, Free Society/, and Scott Dexter and Samir Chopra's /Decoding Liberation/ in addition to foundational works in disability studies, especially those relating to post- and transhumanism. The chapter will also examine communities that have formed around the practice of hacking personal infrastructure, such as [[http://blarbl.blogspot.com/][Blind Arduino]], [[https://talkingarch.tk/][Talking Arch]], and [[https://www.seeingwithsound.com/android.htm][seeingwithsound]].


** utopian?

A number of 19th- and early 20th-century thinkers and writers engaged not only with the idea that technology could serve as a prosthetic for humanity, but that humanity could be a prosthetic for technology. In 1872, Samuel Butler, in the Utopian novel /Erewhon/, suggested not only the former—"[i]f it is wet we are furnished with an organ commonly called an umbrella, and which is designed for the purpose of protecting our clothes or our skins from the injurious effects of rain" (Butler)—but also the latter: "[a]mong themselves the machines will war eternally, but they will still require man as the being through whose agency the struggle will be principally conducted" (Butler). Charles Dickens, in novels such as /Little Dorrit/ and /Dombey and Son/, depicted technological forces such as the railway and social institutions such as the Victorian prison system as self-aware entities that used, processed, and disposed of humanity while working toward their own obscure ends. At the same time, pseudoscientific (or "heterodox") disciplines such as vitalism and spiritualism advanced theories based on forces that pervaded both humanity and the material world. These include the theory of the Odic force, a form of life energy that pervaded all things and that was used to explain phenomena such as will o' wisps and haunted houses. These 19th-century developments, when taken together, represent reactions to increasingly alien social and technological forces and an awareness, if vague, of the new interdependence between the human and the nonhuman.
* TODO you have one job story for utopian?
